### PR TITLE
Fixed /pth: Consistently treat the hash offset to password length.

### LINKED ISSUE #3499: PTH Doesn't work
I've been trying to follow a few articles regarding using the PTH functionality & restricted admin mode.  Nothing seems to work (I've tried on a Kali 2016.1, Kali 2016.2, and an Ubuntu 16 VM) against server 2012 R2, and Server 2012.  

I get the following when I attempt to connect.  
**\* Error in `xfreerdp': free(): invalid next size (fast): 0x00007fecec05f290 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x77725)[0x7fecfc739725]
/lib/x86_64-linux-gnu/libc.so.6(+0x7ff4a)[0x7fecfc741f4a]
/lib/x86_64-linux-gnu/libc.so.6(cfree+0x4c)[0x7fecfc745abc]
/usr/local/bin/../lib/libwinpr.so.2(+0x95e68)[0x7fecfcb20e68]
/usr/local/bin/../lib/libwinpr.so.2(+0x92de3)[0x7fecfcb1dde3]
/usr/local/bin/../lib/libwinpr.so.2(+0x97671)[0x7fecfcb22671]
/usr/local/bin/../lib/libfreerdp.so.2(+0x68518)[0x7fecfd322518]
/usr/local/bin/../lib/libfreerdp.so.2(+0x6cd9b)[0x7fecfd326d9b]
/usr/local/bin/../lib/libfreerdp.so.2(+0xcaec1)[0x7fecfd384ec1]
/usr/local/bin/../lib/libfreerdp.so.2(+0xd7079)[0x7fecfd391079]
/usr/local/bin/../lib/libfreerdp.so.2(+0xcbe4f)[0x7fecfd385e4f]
/usr/local/bin/../lib/libfreerdp.so.2(+0xbced3)[0x7fecfd376ed3]
/usr/local/bin/../lib/libfreerdp.so.2(freerdp_connect+0x243)[0x7fecfd357adf]
xfreerdp[0x4276ff]
/usr/local/bin/../lib/libwinpr.so.2(+0x87433)[0x7fecfcb12433]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x76fa)[0x7fecfc0866fa]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x6d)[0x7fecfc7c8b5d]
======= Memory map: ========
00400000-00430000 r-xp 00000000 08:01 131791                             /usr/local/bin/xfreerdp
0062f000-00630000 r--p 0002f000 08:01 131791                             /usr/local/bin/xfreerdp
00630000-006b1000 rw-p 00030000 08:01 131791                             /usr/local/bin/xfreerdp
01a57000-01aec000 rw-p 00000000 00:00 0                                  [heap]
7fece4000000-7fece4021000 rw-p 00000000 00:00 0 
7fece4021000-7fece8000000 ---p 00000000 00:00 0 
7fecec000000-7fecec078000 rw-p 00000000 00:00 0 
7fecec078000-7fecf0000000 ---p 00000000 00:00 0 
7fecf0c1c000-7fecf0c33000 r-xp 00000000 08:01 1054283                    /lib/x86_64-linux-gnu/libresolv-2.23.so
7fecf0c33000-7fecf0e33000 ---p 00017000 08:01 1054283                    /lib/x86_64-linux-gnu/libresolv-2.23.so
7fecf0e33000-7fecf0e34000 r--p 00017000 08:01 1054283                    /lib/x86_64-linux-gnu/libresolv-2.23.so
7fecf0e34000-7fecf0e35000 rw-p 00018000 08:01 1054283                    /lib/x86_64-linux-gnu/libresolv-2.23.so
7fecf0e35000-7fecf0e37000 rw-p 00000000 00:00 0 
7fecf0e37000-7fecf0e3c000 r-xp 00000000 08:01 1054228                    /lib/x86_64-linux-gnu/libnss_dns-2.23.so
7fecf0e3c000-7fecf103c000 ---p 00005000 08:01 1054228                    /lib/x86_64-linux-gnu/libnss_dns-2.23.so
7fecf103c000-7fecf103d000 r--p 00005000 08:01 1054228                    /lib/x86_64-linux-gnu/libnss_dns-2.23.so
7fecf103d000-7fecf103e000 rw-p 00006000 08:01 1054228                    /lib/x86_64-linux-gnu/libnss_dns-2.23.so
7fecf103e000-7fecf1040000 r-xp 00000000 08:01 1054236                    /lib/x86_64-linux-gnu/libnss_mdns4_minimal.so.2
7fecf1040000-7fecf123f000 ---p 00002000 08:01 1054236                    /lib/x86_64-linux-gnu/libnss_mdns4_minimal.so.2
7fecf123f000-7fecf1240000 r--p 00001000 08:01 1054236                    /lib/x86_64-linux-gnu/libnss_mdns4_minimal.so.2
7fecf1240000-7fecf1241000 rw-p 00002000 08:01 1054236                    /lib/x86_64-linux-gnu/libnss_mdns4_minimal.so.2
7fecf1241000-7fecf124c000 r-xp 00000000 08:01 1054230                    /lib/x86_64-linux-gnu/libnss_files-2.23.so
7fecf124c000-7fecf144b000 ---p 0000b000 08:01 1054230                    /lib/x86_64-linux-gnu/libnss_files-2.23.so
7fecf144b000-7fecf144c000 r--p 0000a000 08:01 1054230                    /lib/x86_64-linux-gnu/libnss_files-2.23.so
7fecf144c000-7fecf144d000 rw-p 0000b000 08:01 1054230                    /lib/x86_64-linux-gnu/libnss_files-2.23.so
7fecf144d000-7fecf1453000 rw-p 00000000 00:00 0 
7fecf1453000-7fecf1454000 ---p 00000000 00:00 0 
7fecf1454000-7fecf217c000 rw-p 00000000 00:00 0 
7fecf217c000-7fecf2b3b000 r--p 00000000 08:01 135870                     /usr/lib/locale/locale-archive
7fecf2b3b000-7fecf2b5c000 r-xp 00000000 08:01 159588                     /usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0
7fecf2b5c000-7fecf2d5b000 ---p 00021000 08:01 159588                     /usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0
7fecf2d5b000-7fecf2d5c000 r--p 00020000 08:01 159588                     /usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0
7fecf2d5c000-7fecf2d5d000 rw-p 00021000 08:01 159588                     /usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0
7fecf2d5d000-7fecf2d73000 r-xp 00000000 08:01 1054169                    /lib/x86_64-linux-gnu/libgcc_s.so.1
7fecf2d73000-7fecf2f72000 ---p 00016000 08:01 1054169                    /lib/x86_64-linux-gnu/libgcc_s.so.1
7fecf2f72000-7fecf2f73000 rw-p 00015000 08:01 1054169                    /lib/x86_64-linux-gnu/libgcc_s.so.1
7fecf2f73000-7fecf2f7a000 r-xp 00000000 08:01 140411                     /usr/lib/x86_64-linux-gnu/libogg.so.0.8.2
7fecf2f7a000-7fecf317a000 ---p 00007000 08:01 140411                     /usr/lib/x86_64-linux-gnu/libogg.so.0.8.2
7fecf317a000-7fecf317b000 r--p 00007000 08:01 140411                     /usr/lib/x86_64-linux-gnu/libogg.so.0.8.2
7fecf317b000-7fecf317c000 rw-p 00008000 08:01 140411                     /usr/lib/x86_64-linux-gnu/libogg.so.0.8.2
7fecf317c000-7fecf32ee000 r-xp 00000000 08:01 131687                     /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.21
7fecf32ee000-7fecf34ee000 ---p 00172000 08:01 131687                     /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.21
7fecf34ee000-7fecf34f8000 r--p 00172000 08:01 131687                     /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.21
7fecf34f8000-7fecf34fa000 rw-p 0017c000 08:01 131687                     /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.21
7fecf34fa000-7fecf34fe000 rw-p 00000000 00:00 0 
7fecf34fe000-7fecf3508000 r-xp 00000000 08:01 140399                     /usr/lib/x86_64-linux-gnu/libnuma.so.1.0.0
7fecf3508000-7fecf3707000 ---p 0000a000 08:01 140399                     /usr/lib/x86_64-linux-gnu/libnuma.so.1.0.0
7fecf3707000-7fecf3708000 r--p 00009000 08:01 140399                     /usr/lib/x86_64-linux-gnu/libnuma.so.1.0.0
7fecf3708000-7fecf3709000 rw-p 0000a000 08:01 140399                     /usr/lib/x86_64-linux-gnu/libnuma.so.1.0.0
7fecf3709000-7fecf372d000 r-xp 00000000 08:01 1054272                    /lib/x86_64-linux-gnu/libpng12.so.0.54.0
7fecf372d000-7fecf392c000 ---p 00024000 08:01 1054272                    /lib/x86_64-linux-gnu/libpng12.so.0.54.0
7fecf392c000-7fecf392d000 r--p 00023000 08:01 1054272                    /lib/x86_64-linux-gnu/libpng12.so.0.54.0
7fecf392d000-7fecf392e000 rw-p 00024000 08:01 1054272                    /lib/x86_64-linux-gnu/libpng12.so.0.54.0
7fecf392e000-7fecf395c000 r-xp 00000000 08:01 159285                     /usr/lib/x86_64-linux-gnu/libsoxr.so.0.1.1
7fecf395c000-7fecf3b5b000 ---p 0002e000 08:01 159285                     /usr/lib/x86_64-linux-gnu/libsoxr.so.0.1.1
7fecf3b5b000-7fecf3b5d000 r--p 0002d000 08:01 159285                     /usr/lib/x86_64-linux-gnu/libsoxr.so.0.1.1
7fecf3b5d000-7fecf3b5e000 rw-p 0002f000 08:01 159285                     /usr/lib/x86_64-linux-gnu/libsoxr.so.0.1.1
7fecf3b5e000-7fecf3b93000 rw-p 00000000 00:00 0 
7fecf3b93000-7fecf3c0e000 r-xp 00000000 08:01 140417                     /usr/lib/x86_64-linux-gnu/liborc-0.4.so.0.25.0
7fecf3c0e000-7fecf3e0d000 ---p 0007b000 08:01 140417                     /usr/lib/x86_64-linux-gnu/liborc-0.4.so.0.25.0
7fecf3e0d000-7fecf3e0f000 r--p 0007a000 08:01 140417                     /usr/lib/x86_64-linux-gnu/liborc-0.4.so.0.25.0
7fecf3e0f000-7fecf3e13000 rw-p 0007c000 08:01 140417                     /usr/lib/x86_64-linux-gnu/liborc-0.4.so.0.25.0
7fecf3e13000-7fecf3e1a000 r-xp 00000000 08:01 139887                     /usr/lib/x86_64-linux-gnu/libffi.so.6.0.4
7fecf3e1a000-7fecf4019000 ---p 00007000 08:01 139887                     /usr/lib/x86_64-linux-gnu/libffi.so.6.0.4
7fecf4019000-7fecf401a000 r--p 00006000 08:01 139887                     /usr/lib/x86_64-linux-gnu/libffi.so.6.0.4
7fecf401a000-7fecf401b000 rw-p 00007000 08:01 139887                     /usr/lib/x86_64-linux-gnu/libffi.so.6.0.4
7fecf401b000-7fecf4089000 r-xp 00000000 08:01 1054260                    /lib/x86_64-linux-gnu/libpcre.so.3.13.2
7fecf4089000-7fecf4289000 ---p 0006e000 08:01 1054260                    /lib/x86_64-linux-gnu/libpcre.so.3.13.2
7fecf4289000-7fecf428a000 r--p 0006e000 08:01 1054260                    /lib/x86_64-linux-gnu/libpcre.so.3.13.2
7fecf428a000-7fecf428b000 rw-p 0006f000 08:01 1054260                    /lib/x86_64-linux-gnu/libpcre.so.3.13.2
7fecf428b000-7fecf428e000 r-xp 00000000 08:01 140018                     /usr/lib/x86_64-linux-gnu/libgmodule-2.0.so.0.4800.1
7fecf428e000-7fecf448d000 ---p 00003000 08:01 140018                     /usr/lib/x86_64-linux-gnu/libgmodule-2.0.so.0.4800.1
7fecf448d000-7fecf448e000 r--p 00002000 08:01 140018                     /usr/lib/x86_64-linux-gnu/libgmodule-2.0.so.0.4800.1
7fecf448e000-7fecf448f000 rw-p 00003000 08:01 140018                     /usr/lib/x86_64-linux-gnu/libgmodule-2.0.so.0.4800.1
7fecf448f000-7fecf44b0000 r-xp 00000000 08:01 1054198                    /lib/x86_64-linux-gnu/liblzma.so.5.0.0
7fecf44b0000-7fecf46af000 ---p 00021000 08:01 1054198                    /lib/x86_64-linux-gnu/liblzma.so.5.0.0
7fecf46af000-7fecf46b0000 r--p 00020000 08:01 1054198                    /lib/x86_64-linux-gnu/liblzma.so.5.0.0
7fecf46b0000-7fecf46b1000 rw-p 00021000 08:01 1054198                    /lib/x86_64-linux-gnu/liblzma.so.5.0.0
7fecf46b1000-7fecf46cb000 r-xp 00000000 08:01 159234                     /usr/lib/x86_64-linux-gnu/libcrystalhd.so.3.6
7fecf46cb000-7fecf48ca000 ---p 0001a000 08:01 159234                     /usr/lib/x86_64-linux-gnu/libcrystalhd.so.3.6
7fecf48ca000-7fecf48cb000 r--p 00019000 08:01 159234                     /usr/lib/x86_64-linux-gnu/libcrystalhd.so.3.6
7fecf48cb000-7fecf48cc000 rw-p 0001a000 08:01 159234                     /usr/lib/x86_64-linux-gnu/libcrystalhd.so.3.6
7fecf48cc000-7fecf48d9000 r-xp 00000000 08:01 159240                     /usr/lib/x86_64-linux-gnu/libgsm.so.1.0.12
7fecf48d9000-7fecf4ad8000 ---p 0000d000 08:01 159240                     /usr/lib/x86_64-linux-gnu/libgsm.so.1.0.12
7fecf4ad8000-7fecf4ad9000 r--p 0000c000 08:01 159240                     /usr/lib/x86_64-linux-gnu/libgsm.so.1.0.12
7fecf4ad9000-7fecf4ada000 rw-p 0000d000 08:01 159240                     /usr/lib/x86_64-linux-gnu/libgsm.so.1.0.12
7fecf4ada000-7fecf4b1f000 r-xp 00000000 08:01 159258                     /usr/lib/x86_64-linux-gnu/libmp3lame.so.0.0.0
7fecf4b1f000-7fecf4d1f000 ---p 00045000 08:01 159258                     /usr/lib/x86_64-linux-gnu/libmp3lame.so.0.0.0
7fecf4d1f000-7fecf4d20000 r--p 00045000 08:01 159258                     /usr/lib/x86_64-linux-gnu/libmp3lame.so.0.0.0
7fecf4d20000-7fecf4d21000 rw-p 00046000 08:01 159258                     /usr/lib/x86_64-linux-gnu/libmp3lame.so.0.0.0
7fecf4d21000-7fecf4d4f000 rw-p 00000000 00:00 0 
7fecf4d4f000-7fecf4d71000 r-xp 00000000 08:01 159266                     /usr/lib/x86_64-linux-gnu/libopenjpeg.so.1.5.2
7fecf4d71000-7fecf4f70000 ---p 00022000 08:01 159266                     /usr/lib/x86_64-linux-gnu/libopenjpeg.so.1.5.2
7fecf4f70000-7fecf4f71000 r--p 00021000 08:01 159266                     /usr/lib/x86_64-linux-gnu/libopenjpeg.so.1.5.2
7fecf4f71000-7fecf4f72000 rw-p 00022000 08:01 159266                     /usr/lib/x86_64-linux-gnu/libopenjpeg.so.1.5.2
7fecf4f72000-7fecf4fbb000 r-xp 00000000 08:01 140415                     /usr/lib/x86_64-linux-gnu/libopus.so.0.5.2
7fecf4fbb000-7fecf51ba000 ---p 00049000 08:01 140415                     /usr/lib/x86_64-linux-gnu/libopus.so.0.5.2
7fecf51ba000-7fecf51bb000 r--p 00048000 08:01 140415                     /usr/lib/x86_64-linux-gnu/libopus.so.0.5.2
7fecf51bb000-7fecf51bc000 rw-p 00049000 08:01 140415                     /usr/lib/x86_64-linux-gnu/libopus.so.0.5.2
7fecf51bc000-7fecf51d5000 r-xp 00000000 08:01 1054322                    /lib/x86_64-linux-gnu/libz.so.1.2.8
7fecf51d5000-7fecf53d4000 ---p 00019000 08:01 1054322                    /lib/x86_64-linux-gnu/libz.so.1.2.8
7fecf53d4000-7fecf53d5000 r--p 00018000 08:01 1054322                    /lib/x86_64-linux-gnu/libz.so.1.2.8
7fecf53d5000-7fecf53d6000 rw-p 00019000 08:01 1054322                    /lib/x86_64-linux-gnu/libz.so.1.2.8
7fecf53d6000-7fecf54a7000 r-xp 00000000 08:01 159247                     /usr/lib/x86_64-linux-gnu/libschroedinger-1.0.so.0.11.0
7fecf54a7000-7fecf56a7000 ---p 000d1000 08:01 159247                     /usr/lib/x86_64-linux-gnu/libschroedinger-1.0.so.0.11.0
7fecf56a7000-7fecf56a9000 r--p 000d1000 08:01 159247                     /usr/lib/x86_64-linux-gnu/libschroedinger-1.0.so.0.11.0
7fecf56a9000-7fecf56aa000 rw-p 000d3000 08:01 159247                     /usr/lib/x86_64-linux-gnu/libschroedinger-1.0.so.0.11.0
7fecf56aa000-7fecf56ab000 rw-p 00000000 00:00 0 
7fecf56ab000-7fecf56b7000 r-xp 00000000 08:01 159273                     /usr/lib/x86_64-linux-gnu/libshine.so.3.0.1
7fecf56b7000-7fecf58b6000 ---p 0000c000 08:01 159273                     /usr/lib/x86_64-linux-gnu/libshine.so.3.0.1
7fecf58b6000-7fecf58b7000 r--p 0000b000 08:01 159273                     /usr/lib/x86_64-linux-gnu/libshine.so.3.0.1
7fecf58b7000-7fecf58b8000 rw-p 0000c000 08:01 159273                     /usr/lib/x86_64-linux-gnu/libshine.so.3.0.1
7fecf58b8000-7fecf58bf000 r-xp 00000000 08:01 159279                     /usr/lib/x86_64-linux-gnu/libsnappy.so.1.3.0
7fecf58bf000-7fecf5abe000 ---p 00007000 08:01 159279                     /usr/lib/x86_64-linux-gnu/libsnappy.so.1.3.0
7fecf5abe000-7fecf5abf000 r--p 00006000 08:01 159279                     /usr/lib/x86_64-linux-gnu/libsnappy.so.1.3.0
7fecf5abf000-7fecf5ac0000 rw-p 00007000 08:01 159279                     /usr/lib/x86_64-linux-gnu/libsnappy.so.1.3.0
7fecf5ac0000-7fecf5ad7000 r-xp 00000000 08:01 140627                     /usr/lib/x86_64-linux-gnu/libspeex.so.1.5.0
7fecf5ad7000-7fecf5cd7000 ---p 00017000 08:01 140627                     /usr/lib/x86_64-linux-gnu/libspeex.so.1.5.0
7fecf5cd7000-7fecf5cd8000 r--p 00017000 08:01 140627                     /usr/lib/x86_64-linux-gnu/libspeex.so.1.5.0
7fecf5cd8000-7fecf5cd9000 rw-p 00018000 08:01 140627                     /usr/lib/x86_64-linux-gnu/libspeex.so.1.5.0
7fecf5cd9000-7fecf5cf2000 r-xp 00000000 08:01 140664                     /usr/lib/x86_64-linux-gnu/libtheoradec.so.1.1.4
7fecf5cf2000-7fecf5ef1000 ---p 00019000 08:01 140664                     /usr/lib/x86_64-linux-gnu/libtheoradec.so.1.1.4
7fecf5ef1000-7fecf5ef2000 r--p 00018000 08:01 140664                     /usr/lib/x86_64-linux-gnu/libtheoradec.so.1.1.4
7fecf5ef2000-7fecf5ef3000 rw-p 00019000 08:01 140664                     /usr/lib/x86_64-linux-gnu/libtheoradec.so.1.1.4
7fecf5ef3000-7fecf5f31000 r-xp 00000000 08:01 140666                     /usr/lib/x86_64-linux-gnu/libtheoraenc.so.1.1.2
7fecf5f31000-7fecf6130000 ---p 0003e000 08:01 140666                     /usr/lib/x86_64-linux-gnu/libtheoraenc.so.1.1.2
7fecf6130000-7fecf6131000 r--p 0003d000 08:01 140666                     /usr/lib/x86_64-linux-gnu/libtheoraenc.so.1.1.2
7fecf6131000-7fecf6132000 rw-p 0003e000 08:01 140666                     /usr/lib/x86_64-linux-gnu/libtheoraenc.so.1.1.2
7fecf6132000-7fecf6150000 r-xp 00000000 08:01 159297                     /usr/lib/x86_64-linux-gnu/libtwolame.so.0.0.0
7fecf6150000-7fecf634f000 ---p 0001e000 08:01 159297                     /usr/lib/x86_64-linux-gnu/libtwolame.so.0.0.0
7fecf634f000-7fecf6350000 r--p 0001d000 08:01 159297                     /usr/lib/x86_64-linux-gnu/libtwolame.so.0.0.0
7fecf6350000-7fecf6351000 rw-p 0001e000 08:01 159297                     /usr/lib/x86_64-linux-gnu/libtwolame.so.0.0.0
7fecf6351000-7fecf6355000 rw-p 00000000 00:00 0 
7fecf6355000-7fecf637f000 r-xp 00000000 08:01 140759                     /usr/lib/x86_64-linux-gnu/libvorbis.so.0.4.8
7fecf637f000-7fecf657f000 ---p 0002a000 08:01 140759                     /usr/lib/x86_64-linux-gnu/libvorbis.so.0.4.8
7fecf657f000-7fecf6580000 r--p 0002a000 08:01 140759                     /usr/lib/x86_64-linux-gnu/libvorbis.so.0.4.8
7fecf6580000-7fecf6581000 rw-p 0002b000 08:01 140759                     /usr/lib/x86_64-linux-gnu/libvorbis.so.0.4.8
7fecf6581000-7fecf660e000 r-xp 00000000 08:01 140761                     /usr/lib/x86_64-linux-gnu/libvorbisenc.so.2.0.11
7fecf660e000-7fecf680d000 ---p 0008d000 08:01 140761                     /usr/lib/x86_64-linux-gnu/libvorbisenc.so.2.0.11
7fecf680d000-7fecf6829000 r--p 0008c000 08:01 140761                     /usr/lib/x86_64-linux-gnu/libvorbisenc.so.2.0.11
7fecf6829000-7fecf682a000 rw-p 000a8000 08:01 140761                     /usr/lib/x86_64-linux-gnu/libvorbisenc.so.2.0.11
7fecf682a000-7fecf6a49000 r-xp 00000000 08:01 140766                     /usr/lib/x86_64-linux-gnu/libvpx.so.3.0.0
7fecf6a49000-7fecf6c48000 ---p 0021f000 08:01 140766                     /usr/lib/x86_64-linux-gnu/libvpx.so.3.0.0
7fecf6c48000-7fecf6c4a000 r--p 0021e000 08:01 140766                     /usr/lib/x86_64-linux-gnu/libvpx.so.3.0.0
7fecf6c4a000-7fecf6c4b000 rw-p 00220000 08:01 140766                     /usr/lib/x86_64-linux-gnu/libvpx.so.3.0.0
7fecf6c4b000-7fecf6c4e000 rw-p 00000000 00:00 0 
7fecf6c4e000-7fecf6c76000 r-xp 00000000 08:01 140772                     /usr/lib/x86_64-linux-gnu/libwavpack.so.1.1.7
7fecf6c76000-7fecf6e75000 ---p 00028000 08:01 140772                     /usr/lib/x86_64-linux-gnu/libwavpack.so.1.1.7
7fecf6e75000-7fecf6e76000 r--p 00027000 08:01 140772                     /usr/lib/x86_64-linux-gnu/libwavpack.so.1.1.7
7fecf6e76000-7fecf6e77000 rw-p 00028000 08:01 140772                     /usr/lib/x86_64-linux-gnu/libwavpack.so.1.1.7
7fecf6e77000-7fecf6ed0000 r-xp 00000000 08:01 140786                     /usr/lib/x86_64-linux-gnu/libwebp.so.5.0.4
7fecf6ed0000-7fecf70d0000 ---p 00059000 08:01 140786                     /usr/lib/x86_64-linux-gnu/libwebp.so.5.0.4
7fecf70d0000-7fecf70d1000 r--p 00059000 08:01 140786                     /usr/lib/x86_64-linux-gnu/libwebp.so.5.0.4
7fecf70d1000-7fecf70d3000 rw-p 0005a000 08:01 140786                     /usr/lib/x86_64-linux-gnu/libwebp.so.5.0.4
7fecf70d3000-7fecf71fb000 r-xp 00000000 08:01 159310                     /usr/lib/x86_64-linux-gnu/libx264.so.148
7fecf71fb000-7fecf73fa000 ---p 00128000 08:01 159310                     /usr/lib/x86_64-linux-gnu/libx264.so.148
7fecf73fa000-7fecf73fb000 r--p 00127000 08:01 159310                     /usr/lib/x86_64-linux-gnu/libx264.so.148
7fecf73fb000-7fecf73fc000 rw-p 00128000 08:01 159310                     /usr/lib/x86_64-linux-gnu/libx264.so.148
7fecf73fc000-7fecf7477000 rw-p 00000000 00:00 0 
7fecf7477000-7fecf7e84000 r-xp 00000000 08:01 159315                     /usr/lib/x86_64-linux-gnu/libx265.so.79
7fecf7e84000-7fecf8083000 ---p 00a0d000 08:01 159315                     /usr/lib/x86_64-linux-gnu/libx265.so.79
7fecf8083000-7fecf8086000 r--p 00a0c000 08:01 159315                     /usr/lib/x86_64-linux-gnu/libx265.so.79
7fecf8086000-7fecf8089000 rw-p 00a0f000 08:01 159315                     /usr/lib/x86_64-linux-gnu/libx265.so.79
7fecf8089000-7fecf8096000 rw-p 00000000 00:00 0 
7fecf8096000-7fecf8137000 r-xp 00000000 08:01 159321                     /usr/lib/x86_64-linux-gnu/libxvidcore.so.4.3
7fecf8137000-7fecf8336000 ---p 000a1000 08:01 159321                     /usr/lib/x86_64-linux-gnu/libxvidcore.so.4.3
7fecf8336000-7fecf8337000 r--p 000a0000 08:01 159321                     /usr/lib/x86_64-linux-gnu/libxvidcore.so.4.3
7fecf8337000-7fecf8341000 rw-p 000a1000 08:01 159321                     /usr/lib/x86_64-linux-gnu/libxvidcore.so.4.3
7fecf8341000-7fecf83aa000 rw-p 00000000 00:00 0 
7fecf83aa000-7fecf8421000 r-xp 00000000 08:01 159328                     /usr/lib/x86_64-linux-gnu/libzvbi.so.0.13.2
7fecf8421000-7fecf8620000 ---p 00077000 08:01 159328                     /usr/lib/x86_64-linux-gnu/libzvbi.so.0.13.2
7fecf8620000-7fecf8629000 r--p 00076000 08:01 159328                     /usr/lib/x86_64-linux-gnu/libzvbi.so.0.13.2
7fecf8629000-7fecf8635000 rw-p 0007f000 08:01 159328                     /usr/lib/x86_64-linux-gnu/libzvbi.so.0.13.2
7fecf8635000-7fecf8650000 r-xp 00000000 08:01 159303                     /usr/lib/x86_64-linux-gnu/libva.so.1.3900.0
7fecf8650000-7fecf884f000 ---p 0001b000 08:01 159303                     /usr/lib/x86_64-linux-gnu/libva.so.1.3900.0
7fecf884f000-7fecf8850000 r--p 0001a000 08:01 159303                     /usr/lib/x86_64-linux-gnu/libva.so.1.3900.0
7fecf8850000-7fecf8851000 rw-p 0001b000 08:01 159303                     /usr/lib/x86_64-linux-gnu/libva.so.1.3900.0
7fecf8851000-7fecf886b000 r-xp 00000000 08:01 159291                     /usr/lib/x86_64-linux-gnu/libswresample-ffmpeg.so.1.2.101
7fecf886b000-7fecf8a6a000 ---p 0001a000 08:01 159291                     /usr/lib/x86_64-linux-gnu/libswresample-ffmpeg.so.1.2.101
7fecf8a6a000-7fecf8a6c000 r--p 00019000 08:01 159291                     /usr/lib/x86_64-linux-gnu/libswresample-ffmpeg.so.1.2.101
7fecf8a6c000-7fecf8a6d000 rw-p 0001b000 08:01 159291                     /usr/lib/x86_64-linux-gnu/libswresample-ffmpeg.so.1.2.101
7fecf8a6d000-7fecf8a72000 r-xp 00000000 08:01 139515                     /usr/lib/x86_64-linux-gnu/libXdmcp.so.6.0.0
7fecf8a72000-7fecf8c71000 ---p 00005000 08:01 139515                     /usr/lib/x86_64-linux-gnu/libXdmcp.so.6.0.0
7fecf8c71000-7fecf8c72000 r--p 00004000 08:01 139515                     /usr/lib/x86_64-linux-gnu/libXdmcp.so.6.0.0
7fecf8c72000-7fecf8c73000 rw-p 00005000 08:01 139515                     /usr/lib/x86_64-linux-gnu/libXdmcp.so.6.0.0
7fecf8c73000-7fecf8c75000 r-xp 00000000 08:01 139504                     /usr/lib/x86_64-linux-gnu/libXau.so.6.0.0
7fecf8c75000-7fecf8e75000 ---p 00002000 08:01 139504                     /usr/lib/x86_64-linux-gnu/libXau.so.6.0.0
7fecf8e75000-7fecf8e76000 r--p 00002000 08:01 139504                     /usr/lib/x86_64-linux-gnu/libXau.so.6.0.0
7fecf8e76000-7fecf8e77000 rw-p 00003000 08:01 139504                     /usr/lib/x86_64-linux-gnu/libXau.so.6.0.0
7fecf8e77000-7fecf8e9b000 r-xp 00000000 08:01 140888                     /usr/lib/x86_64-linux-gnu/libxkbfile.so.1.0.2
7fecf8e9b000-7fecf909b000 ---p 00024000 08:01 140888                     /usr/lib/x86_64-linux-gnu/libxkbfile.so.1.0.2
7fecf909b000-7fecf909c000 r--p 00024000 08:01 140888                     /usr/lib/x86_64-linux-gnu/libxkbfile.so.1.0.2
7fecf909c000-7fecf909d000 rw-p 00025000 08:01 140888                     /usr/lib/x86_64-linux-gnu/libxkbfile.so.1.0.2
7fecf909d000-7fecf92cc000 r-xp 00000000 08:01 1048666                    /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
7fecf92cc000-7fecf94cb000 ---p 0022f000 08:01 1048666                    /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
7fecf94cb000-7fecf94e7000 r--p 0022e000 08:01 1048666                    /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
7fecf94e7000-7fecf94f4000 rw-p 0024a000 08:01 1048666                    /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
7fecf94f4000-7fecf94f8000 rw-p 00000000 00:00 0 
7fecf94f8000-7fecf9557000 r-xp 00000000 08:01 1054030                    /lib/x86_64-linux-gnu/libssl.so.1.0.0
7fecf9557000-7fecf9756000 ---p 0005f000 08:01 1054030                    /lib/x86_64-linux-gnu/libssl.so.1.0.0
7fecf9756000-7fecf975a000 r--p 0005e000 08:01 1054030                    /lib/x86_64-linux-gnu/libssl.so.1.0.0
7fecf975a000-7fecf9761000 rw-p 00062000 08:01 1054030                    /lib/x86_64-linux-gnu/libssl.so.1.0.0
7fecf9761000-7fecf985a000 r-xp 00000000 08:01 139596                     /usr/lib/x86_64-linux-gnu/libasound.so.2.0.0
7fecf985a000-7fecf9a59000 ---p 000f9000 08:01 139596                     /usr/lib/x86_64-linux-gnu/libasound.so.2.0.0
7fecf9a59000-7fecf9a60000 r--p 000f8000 08:01 139596                     /usr/lib/x86_64-linux-gnu/libasound.so.2.0.0
7fecf9a60000-7fecf9a61000 rw-p 000ff000 08:01 139596                     /usr/lib/x86_64-linux-gnu/libasound.so.2.0.0
7fecf9a61000-7fecf9adc000 r-xp 00000000 08:01 140113                     /usr/lib/x86_64-linux-gnu/libgstvideo-1.0.so.0.802.0
7fecf9adc000-7fecf9cdb000 ---p 0007b000 08:01 140113                     /usr/lib/x86_64-linux-gnu/libgstvideo-1.0.so.0.802.0
7fecf9cdb000-7fecf9ce4000 r--p 0007a000 08:01 140113                     /usr/lib/x86_64-linux-gnu/libgstvideo-1.0.so.0.802.0
7fecf9ce4000-7fecf9ce5000 rw-p 00083000 08:01 140113                     /usr/lib/x86_64-linux-gnu/libgstvideo-1.0.so.0.802.0
7fecf9ce5000-7fecf9ce6000 rw-p 00000000 00:00 0 
7fecf9ce6000-7fecf9cf2000 r-xp 00000000 08:01 140081                     /usr/lib/x86_64-linux-gnu/libgstapp-1.0.so.0.802.0
7fecf9cf2000-7fecf9ef2000 ---p 0000c000 08:01 140081                     /usr/lib/x86_64-linux-gnu/libgstapp-1.0.so.0.802.0
7fecf9ef2000-7fecf9ef3000 r--p 0000c000 08:01 140081                     /usr/lib/x86_64-linux-gnu/libgstapp-1.0.so.0.802.0
7fecf9ef3000-7fecf9ef4000 rw-p 0000d000 08:01 140081                     /usr/lib/x86_64-linux-gnu/libgstapp-1.0.so.0.802.0
7fecf9ef4000-7fecf9f57000 r-xp 00000000 08:01 140085                     /usr/lib/x86_64-linux-gnu/libgstbase-1.0.so.0.802.0
7fecf9f57000-7fecfa156000 ---p 00063000 08:01 140085                     /usr/lib/x86_64-linux-gnu/libgstbase-1.0.so.0.802.0
7fecfa156000-7fecfa157000 r--p 00062000 08:01 140085                     /usr/lib/x86_64-linux-gnu/libgstbase-1.0.so.0.802.0
7fecfa157000-7fecfa158000 rw-p 00063000 08:01 140085                     /usr/lib/x86_64-linux-gnu/libgstbase-1.0.so.0.802.0
7fecfa158000-7fecfa1aa000 r-xp 00000000 08:01 140042                     /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.4800.1
7fecfa1aa000-7fecfa3a9000 ---p 00052000 08:01 140042                     /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.4800.1
7fecfa3a9000-7fecfa3aa000 r--p 00051000 08:01 140042                     /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.4800.1
7fecfa3aa000-7fecfa3ab000 rw-p 00052000 08:01 140042                     /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.4800.1
7fecfa3ab000-7fecfa4ba000 r-xp 00000000 08:01 1054173                    /lib/x86_64-linux-gnu/libglib-2.0.so.0.4800.1
7fecfa4ba000-7fecfa6b9000 ---p 0010f000 08:01 1054173                    /lib/x86_64-linux-gnu/libglib-2.0.so.0.4800.1
7fecfa6b9000-7fecfa6ba000 r--p 0010e000 08:01 1054173                    /lib/x86_64-linux-gnu/libglib-2.0.so.0.4800.1
7fecfa6ba000-7fecfa6bb000 rw-p 0010f000 08:01 1054173                    /lib/x86_64-linux-gnu/libglib-2.0.so.0.4800.1
7fecfa6bb000-7fecfa6bc000 rw-p 00000000 00:00 0 
7fecfa6bc000-7fecfa7dd000 r-xp 00000000 08:01 140101                     /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0.802.0
7fecfa7dd000-7fecfa9dc000 ---p 00121000 08:01 140101                     /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0.802.0
7fecfa9dc000-7fecfa9e2000 r--p 00120000 08:01 140101                     /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0.802.0
7fecfa9e2000-7fecfa9e4000 rw-p 00126000 08:01 140101                     /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0.802.0
7fecfa9e4000-7fecfa9e6000 rw-p 00000000 00:00 0 
7fecfa9e6000-7fecfaa3b000 r-xp 00000000 08:01 159253                     /usr/lib/x86_64-linux-gnu/libavutil-ffmpeg.so.54.31.100
7fecfaa3b000-7fecfac3b000 ---p 00055000 08:01 159253                     /usr/lib/x86_64-linux-gnu/libavutil-ffmpeg.so.54.31.100
7fecfac3b000-7fecfac41000 r--p 00055000 08:01 159253                     /usr/lib/x86_64-linux-gnu/libavutil-ffmpeg.so.54.31.100
7fecfac41000-7fecfac42000 rw-p 0005b000 08:01 159253                     /usr/lib/x86_64-linux-gnu/libavutil-ffmpeg.so.54.31.100
7fecfac42000-7fecfac55000 rw-p 00000000 00:00 0 
7fecfac55000-7fecfb77f000 r-xp 00000000 08:01 159336                     /usr/lib/x86_64-linux-gnu/libavcodec-ffmpeg.so.56.60.100
7fecfb77f000-7fecfb97e000 ---p 00b2a000 08:01 159336                     /usr/lib/x86_64-linux-gnu/libavcodec-ffmpeg.so.56.60.100
7fecfb97e000-7fecfb9a9000 r--p 00b29000 08:01 159336                     /usr/lib/x86_64-linux-gnu/libavcodec-ffmpeg.so.56.60.100
7fecfb9a9000-7fecfb9cc000 rw-p 00b54000 08:01 159336                     /usr/lib/x86_64-linux-gnu/libavcodec-ffmpeg.so.56.60.100
7fecfb9cc000-7fecfc07f000 rw-p 00000000 00:00 0 
7fecfc07f000-7fecfc097000 r-xp 00000000 08:01 1054277                    /lib/x86_64-linux-gnu/libpthread-2.23.so
7fecfc097000-7fecfc296000 ---p 00018000 08:01 1054277                    /lib/x86_64-linux-gnu/libpthread-2.23.so
7fecfc296000-7fecfc297000 r--p 00017000 08:01 1054277                    /lib/x86_64-linux-gnu/libpthread-2.23.so
7fecfc297000-7fecfc298000 rw-p 00018000 08:01 1054277                    /lib/x86_64-linux-gnu/libpthread-2.23.so
7fecfc298000-7fecfc29c000 rw-p 00000000 00:00 0 
7fecfc29c000-7fecfc29f000 r-xp 00000000 08:01 1054155                    /lib/x86_64-linux-gnu/libdl-2.23.so
7fecfc29f000-7fecfc49e000 ---p 00003000 08:01 1054155                    /lib/x86_64-linux-gnu/libdl-2.23.so
7fecfc49e000-7fecfc49f000 r--p 00002000 08:01 1054155                    /lib/x86_64-linux-gnu/libdl-2.23.so
7fecfc49f000-7fecfc4a0000 rw-p 00003000 08:01 1054155                    /lib/x86_64-linux-gnu/libdl-2.23.so
7fecfc4a0000-7fecfc4c1000 r-xp 00000000 08:01 140882                     /usr/lib/x86_64-linux-gnu/libxcb.so.1.1.0
7fecfc4c1000-7fecfc6c0000 ---p 00021000 08:01 140882                     /usr/lib/x86_64-linux-gnu/libxcb.so.1.1.0
7fecfc6c0000-7fecfc6c1000 r--p 00020000 08:01 140882                     /usr/lib/x86_64-linux-gnu/libxcb.so.1.1.0
7fecfc6c1000-7fecfc6c2000 rw-p 00021000 08:01 140882                     /usr/lib/x86_64-linux-gnu/libxcb.so.1.1.0
7fecfc6c2000-7fecfc882000 r-xp 00000000 08:01 1054131                    /lib/x86_64-linux-gnu/libc-2.23.so
7fecfc882000-7fecfca81000 ---p 001c0000 08:01 1054131                    /lib/x86_64-linux-gnu/libc-2.23.so
7fecfca81000-7fecfca85000 r--p 001bf000 08:01 1054131                    /lib/x86_64-linux-gnu/libc-2.23.so
7fecfca85000-7fecfca87000 rw-p 001c3000 08:01 1054131                    /lib/x86_64-linux-gnu/libc-2.23.so
7fecfca87000-7fecfca8b000 rw-p 00000000 00:00 0 
7fecfca8b000-7fecfcb8b000 r-xp 00000000 08:01 131104                     /usr/local/lib/libwinpr.so.2.0.0
7fecfcb8b000-7fecfcd8b000 ---p 00100000 08:01 131104                     /usr/local/lib/libwinpr.so.2.0.0
7fecfcd8b000-7fecfcd92000 r--p 00100000 08:01 131104                     /usr/local/lib/libwinpr.so.2.0.0
7fecfcd92000-7fecfcd98000 rw-p 00107000 08:01 131104                     /usr/local/lib/libwinpr.so.2.0.0
7fecfcd98000-7fecfcda9000 rw-p 00000000 00:00 0 
7fecfcda9000-7fecfcdb0000 r-xp 00000000 08:01 1054285                    /lib/x86_64-linux-gnu/librt-2.23.so
7fecfcdb0000-7fecfcfaf000 ---p 00007000 08:01 1054285                    /lib/x86_64-linux-gnu/librt-2.23.so
7fecfcfaf000-7fecfcfb0000 r--p 00006000 08:01 Aborted (core dumped)

### PR DESCRIPTION
**Pull request by akallabeth**
Fixes #3499

### CODE REVIEW

**Comment by Rogdham** [comment]
*Following comments from #3499...*

Just tried again, I guess the debug line you want is `NLA begin failed`. If you want me to run some more commands, tell me.

***

```
$ git rev-parse HEAD
b59b0a4425485700bdc3b2301653308cead22c82
$ WLOG_LEVEL=DEBUG ./xfreerdp /u:administrator /d:W /pth:7337532fd3bf3abfaef5a9b5bb05a9d8 /v:192.168.56.101
[09:22:38:544] [2797:2797] [DEBUG][com.freerdp.utils] - Registering signal hook...
[09:22:38:547] [2797:2797] [DEBUG][com.freerdp.client.common.cmdline] - windows: 0/1 posix: -1000/0 compat: -1000/0
[09:22:38:547] [2797:2798] [DEBUG][com.freerdp.channels.cliprdr.client] - VirtualChannelEntryEx
[09:22:38:547] [2797:2798] [INFO][com.freerdp.client.common.cmdline] - loading channelEx cliprdr
[09:22:38:548] [2797:2798] [INFO][com.freerdp.client.x11] - Property 335 does not exist
[09:22:38:548] [2797:2798] [DEBUG][com.freerdp.client.x11] - Searching for XInput pointer device
[09:22:38:548] [2797:2798] [DEBUG][com.freerdp.client.x11] - Pointer device: 11
[09:22:38:550] [2797:2798] [DEBUG][com.freerdp.core.nego] - Enabling security layer negotiation: TRUE
[09:22:38:550] [2797:2798] [DEBUG][com.freerdp.core.nego] - Enabling restricted admin mode: TRUE
[09:22:38:550] [2797:2798] [DEBUG][com.freerdp.core.nego] - Enabling RDP security: TRUE
[09:22:38:550] [2797:2798] [DEBUG][com.freerdp.core.nego] - Enabling TLS security: TRUE
[09:22:38:550] [2797:2798] [DEBUG][com.freerdp.core.nego] - Enabling NLA security: TRUE
[09:22:38:550] [2797:2798] [DEBUG][com.freerdp.core.nego] - Enabling NLA extended security: FALSE
[09:22:38:550] [2797:2798] [DEBUG][com.freerdp.core.nego] - state: NEGO_STATE_NLA
[09:22:38:550] [2797:2798] [DEBUG][com.freerdp.core.nego] - Attempting NLA security
[09:22:38:550] [2797:2798] [DEBUG][com.freerdp.core] - connecting to peer 192.168.56.101
[09:22:38:550] [2797:2798] [DEBUG][com.freerdp.core.nego] - RequestedProtocols: 3
[09:22:38:552] [2797:2798] [DEBUG][com.freerdp.core.nego] - RDP_NEG_RSP
[09:22:38:552] [2797:2798] [DEBUG][com.freerdp.core.nego] - selected_protocol: 2
[09:22:38:552] [2797:2798] [DEBUG][com.freerdp.core.nego] - state: NEGO_STATE_FINAL
[09:22:38:552] [2797:2798] [DEBUG][com.freerdp.core.nego] - Negotiated NLA security
[09:22:38:552] [2797:2798] [DEBUG][com.freerdp.core.nego] - nego_security_connect with PROTOCOL_NLA
[09:22:38:554] [2797:2798] [DEBUG][com.winpr.utils] - Could not open SAM file!
[09:22:38:554] [2797:2798] [ERROR][com.freerdp.core.transport] - NLA begin failed
[09:22:38:554] [2797:2798] [ERROR][com.freerdp.core] - freerdp_set_last_error ERRCONNECT_AUTHENTICATION_FAILED [0x00020009]
[09:22:38:554] [2797:2798] [DEBUG][com.freerdp.core.nego] - Failed to connect with NLA security
```

> Might be SSL related, which version (and how compiled) are you using?

```
$ openssl version
OpenSSL 1.1.0h  27 Mar 2018
```

**Comment by Rogdham** [comment]
Same error when build with OpenSSL 1.0:

```
$ openssl-1.0 version
OpenSSL 1.0.2o  27 Mar 2018
$ ldd xfreerdp | grep ssl
	libssl.so.1.0.0 => /usr/lib/libssl.so.1.0.0 (0x00007f9245e46000)
$ git rev-parse HEAD
b59b0a4425485700bdc3b2301653308cead22c82
$ WLOG_LEVEL=DEBUG ./xfreerdp /u:administrator /d:W /pth:7337532fd3bf3abfaef5a9b5bb05a9d8 /v:192.168.56.101
[09:37:26:250] [13671:13671] [DEBUG][com.freerdp.utils] - Registering signal hook...
[09:37:26:253] [13671:13671] [DEBUG][com.freerdp.client.common.cmdline] - windows: 0/1 posix: -1000/0 compat: -1000/0
[09:37:26:254] [13671:13672] [DEBUG][com.freerdp.channels.cliprdr.client] - VirtualChannelEntryEx
[09:37:26:254] [13671:13672] [INFO][com.freerdp.client.common.cmdline] - loading channelEx cliprdr
[09:37:26:254] [13671:13672] [INFO][com.freerdp.client.x11] - Property 335 does not exist
[09:37:26:254] [13671:13672] [DEBUG][com.freerdp.client.x11] - Searching for XInput pointer device
[09:37:26:255] [13671:13672] [DEBUG][com.freerdp.client.x11] - Pointer device: 11
[09:37:26:256] [13671:13672] [DEBUG][com.freerdp.core.nego] - Enabling security layer negotiation: TRUE
[09:37:26:256] [13671:13672] [DEBUG][com.freerdp.core.nego] - Enabling restricted admin mode: TRUE
[09:37:26:256] [13671:13672] [DEBUG][com.freerdp.core.nego] - Enabling RDP security: TRUE
[09:37:26:256] [13671:13672] [DEBUG][com.freerdp.core.nego] - Enabling TLS security: TRUE
[09:37:26:256] [13671:13672] [DEBUG][com.freerdp.core.nego] - Enabling NLA security: TRUE
[09:37:26:256] [13671:13672] [DEBUG][com.freerdp.core.nego] - Enabling NLA extended security: FALSE
[09:37:26:256] [13671:13672] [DEBUG][com.freerdp.core.nego] - state: NEGO_STATE_NLA
[09:37:26:256] [13671:13672] [DEBUG][com.freerdp.core.nego] - Attempting NLA security
[09:37:26:256] [13671:13672] [DEBUG][com.freerdp.core] - connecting to peer 192.168.56.101
[09:37:26:256] [13671:13672] [DEBUG][com.freerdp.core.nego] - RequestedProtocols: 3
[09:37:26:258] [13671:13672] [DEBUG][com.freerdp.core.nego] - RDP_NEG_RSP
[09:37:26:258] [13671:13672] [DEBUG][com.freerdp.core.nego] - selected_protocol: 2
[09:37:26:258] [13671:13672] [DEBUG][com.freerdp.core.nego] - state: NEGO_STATE_FINAL
[09:37:26:258] [13671:13672] [DEBUG][com.freerdp.core.nego] - Negotiated NLA security
[09:37:26:258] [13671:13672] [DEBUG][com.freerdp.core.nego] - nego_security_connect with PROTOCOL_NLA
[09:37:26:260] [13671:13672] [DEBUG][com.winpr.utils] - Could not open SAM file!
[09:37:26:260] [13671:13672] [ERROR][com.freerdp.core.transport] - NLA begin failed
[09:37:26:260] [13671:13672] [ERROR][com.freerdp.core] - freerdp_set_last_error ERRCONNECT_AUTHENTICATION_FAILED [0x00020009]
[09:37:26:260] [13671:13672] [DEBUG][com.freerdp.core.nego] - Failed to connect with NLA security
```

**Comment by akallabeth** [comment]
@Rogdham Ok, think I found it.
you don't provide a password, therefore the call to `sspi_SetAuthIdentity` fails before the hash is handled.

**Comment by Rogdham** [comment]
I have an error building:

```
/tmp/freerdp/libfreerdp/core/nla.c: In function 'nla_client_init':
/tmp/freerdp/libfreerdp/core/nla.c:281:7: error: 'identity' undeclared (first use in this function); did you mean 'entry'?
       identity->PasswordLength += LB_PASSWORD_MAX_LENGTH;
       ^~~~~~~~
       entry
```

**Comment by akallabeth** [comment]
@Rogdham oops, typo ^^

File: libfreerdp/core/nla.c [hunk 1]
```diff
@@ -257,41 +262,37 @@ static int nla_client_init(rdpNla* nla)
...
-					 */
-					identity->PasswordLength = 32 * 64; /* 2048 */
+					if (strlen(settings->PasswordHash) == 32)
+					{
+						if (sspi_SetAuthIdentity(nla->identity, settings->Username, settings->Domain,
+						                         settings->PasswordHash) < 0)
+							return -1;
+
+						/**
+						 * Multiply password hash length by 64 to obtain a length exceeding
```
Comment (mfleisz) [inline libfreerdp/core/nla.c]: Comment should be updated to reflect the code change
