### PR TITLE
Fixed #4357: NTLM debug message.

### LINKED ISSUE #4357: Master does not build: 'credentials’ undeclared
Error:

ntlm_compute.c:404:49: error: ‘credentials’ undeclared (first use in this function)
  WLog_DBG(TAG, "Password (length = %"PRIu32")", credentials->identity.PasswordL

```
Build cmd:
cmake -C /var/tmp/portage/net-misc/freerdp-9999/work/freerdp-9999_build/gentoo_common_config.cmake -G Unix Makefiles -DCMAKE_INSTALL_PREFIX=/usr -DBUILD_TESTING=no -DCHANNEL_URBDRC=yes -DWITH_ALSA=yes -DWITH_CCACHE=OFF -DWITH_CLIENT=yes -DWITH_CUPS=yes -DWITH_DEBUG_ALL=yes -DWITH_MANPAGES=no -DWITH_FFMPEG=yes -DWITH_GSTREAMER_1_0=yes -DWITH_JPEG=yes -DWITH_NEON=no -DWITH_OPENH264=yes -DWITH_PULSE=yes -DWITH_SERVER=yes -DWITH_PCSC=no -DWITH_LIBSYSTEMD=no -DWITH_X11=yes -DWITH_XINERAMA=yes -DWITH_XV=yes -DWITH_WAYLAND=no -DCMAKE_BUILD_TYPE=Gentoo -DCMAKE_USER_MAKE_RULES_OVERRIDE=/var/tmp/portage/net-misc/freerdp-9999/work/freerdp-9999_build/gentoo_rules.cmake -DCMAKE_TOOLCHAIN_FILE=/var/tmp/portage/net-misc/freerdp-9999/work/freerdp-9999_build/gentoo_toolchain.cmake  /var/tmp/portage/net-misc/freerdp-9999/work/freerdp-9999
loading initial cache file /var/tmp/portage/net-misc/freerdp-9999/work/freerdp-9999_build/gentoo_common_config.cmake
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/x86_64-pc-linux-gnu-gcc
-- Check for working C compiler: /usr/bin/x86_64-pc-linux-gnu-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/x86_64-pc-linux-gnu-g++
-- Check for working CXX compiler: /usr/bin/x86_64-pc-linux-gnu-g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: x86_64-pc-linux-gnu-pkg-config (found version "0.29.2") 
FREERDP_VERSION=2.0.0-dev2
-- Git Revision 792a75c46
-- Looking for __x86_64__
-- Looking for __x86_64__ - found
-- Performing Test Wno-unused-result
-- Performing Test Wno-unused-result - Success
-- Performing Test Wno-unused-but-set-variable
-- Performing Test Wno-unused-but-set-variable - Success
-- Performing Test Wno-deprecated-declarations
-- Performing Test Wno-deprecated-declarations - Success
-- Performing Test Wno-deprecated-declarationsCXX
-- Performing Test Wno-deprecated-declarationsCXX - Success
-- GCC default symbol visibility: hidden
-- Performing Test Wimplicit-function-declaration
-- Performing Test Wimplicit-function-declaration - Success
-- Performing Test Wredundant-decls
-- Performing Test Wredundant-decls - Success
-- Looking for include file fcntl.h
-- Looking for include file fcntl.h - found
-- Looking for include file unistd.h
-- Looking for include file unistd.h - found
-- Looking for include file execinfo.h
-- Looking for include file execinfo.h - found
-- Looking for include file inttypes.h
-- Looking for include file inttypes.h - found
-- Looking for include file sys/modem.h
-- Looking for include file sys/modem.h - not found
-- Looking for include file sys/filio.h
-- Looking for include file sys/filio.h - not found
-- Looking for include file sys/sockio.h
-- Looking for include file sys/sockio.h - not found
-- Looking for include file sys/strtio.h
-- Looking for include file sys/strtio.h - not found
-- Looking for include file sys/select.h
-- Looking for include file sys/select.h - found
-- Looking for include file syslog.h
-- Looking for include file syslog.h - found
-- Performing Test HAVE_TM_GMTOFF
-- Performing Test HAVE_TM_GMTOFF - Success
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Looking for pthread_mutex_timedlock
-- Looking for pthread_mutex_timedlock - not found
-- Looking for pthread_mutex_timedlock in pthread
-- Looking for pthread_mutex_timedlock in pthread - found
-- Looking for include file sys/eventfd.h
-- Looking for include file sys/eventfd.h - found
-- Looking for include file sys/eventfd.h
-- Looking for include file sys/eventfd.h - found
-- Looking for eventfd_read
-- Looking for eventfd_read - found
-- Looking for include file sys/timerfd.h
-- Looking for include file sys/timerfd.h - found
-- Looking for include file poll.h
-- Looking for include file poll.h - found
-- Looking for ceill
-- Looking for ceill - found
-- Skipping recommended feature libsystemd for systemd journal appender (allows to export wLog to systemd journal)
-- Finding recommended feature X11 for X11 (X11 client and server)
--     Disable feature X11 using "-DWITH_X11=OFF"
-- Found X11: /usr/lib/libX11.so  
-- Skipping recommended feature Wayland for Wayland (Wayland client)
-- Skipping optional feature DirectFB for DirectFB (DirectFB client)
--     Enable feature DirectFB using "-DWITH_DIRECTFB=ON"
-- Finding required feature ZLIB for compression (data compression)
-- Found ZLIB: /usr/lib/libz.so (found version "1.2.11") 
-- Finding required feature OpenSSL for cryptography (encryption, certificate validation, hashing functions)
-- Found OpenSSL: /usr/lib64/libssl.so;/usr/lib64/libcrypto.so (found version "1.0.2n") 
-- Skipping optional feature MbedTLS for cryptography (encryption, certificate validation, hashing functions)
--     Enable feature MbedTLS using "-DWITH_MBEDTLS=ON"
-- Skipping optional feature OpenSLES for multimedia (OpenSLES audio / video)
--     Enable feature OpenSLES using "-DWITH_OPENSLES=ON"
-- Finding recommended feature OSS for sound (audio input, audio output and multimedia redirection)
--     Disable feature OSS using "-DWITH_OSS=OFF"
-- Found OSS Audio
-- Finding recommended feature ALSA for sound (audio input, audio output and multimedia redirection)
--     Disable feature ALSA using "-DWITH_ALSA=OFF"
-- Found ALSA: /usr/lib/libasound.so (found version "1.1.5") 
-- Finding optional feature Pulse for sound (audio input, audio output and multimedia redirection)
-- Checking for module 'libpulse'
--   Found libpulse, version 11.1
-- Found Pulse: /usr/include  
-- Finding optional feature Cups for printing (printer device redirection)
-- Found Cups: /usr/lib/libcups.so (found version "2.1.4") 
-- Skipping optional feature PCSC for smart card (smart card device redirection)
--     Enable feature PCSC using "-DWITH_PCSC=ON"
-- Finding recommended feature FFmpeg for multimedia (multimedia redirection, audio and video playback)
--     Disable feature FFmpeg using "-DWITH_FFMPEG=OFF"
-- Checking for module 'libavcodec'
--   Found libavcodec, version 57.89.100
-- Checking for module 'libavutil'
--   Found libavutil, version 55.58.100
-- Found FFmpeg: TRUE  
-- Skipping optional feature GStreamer_0_10 for multimedia (multimedia redirection, audio and video playback, gstreamer 0.10 version)
--     Enable feature GStreamer_0_10 using "-DWITH_GSTREAMER_0_10=ON"
-- Finding recommended feature GStreamer_1_0 for multimedia (multimedia redirection, audio and video playback)
--     Disable feature GStreamer_1_0 using "-DWITH_GSTREAMER_1_0=OFF"
-- Checking for module 'glib-2.0'
--   Found glib-2.0, version 2.50.3
-- Found Glib 
-- Checking for module 'gstreamer-1.0 >= 1.0.5'
--   Found gstreamer-1.0 , version 1.12.3
-- Checking for module 'gstreamer-base-1.0 >= 1.0.5'
--   Found gstreamer-base-1.0 , version 1.12.3
-- Checking for module 'gstreamer-app-1.0 >= 1.0.5'
--   Found gstreamer-app-1.0 , version 1.12.3
-- Checking for module 'gstreamer-audio-1.0 >= 1.0.5'
--   Found gstreamer-audio-1.0 , version 1.12.3
-- Checking for module 'gstreamer-fft-1.0 >= 1.0.5'
--   Found gstreamer-fft-1.0 , version 1.12.3
-- Checking for module 'gstreamer-pbutils-1.0 >= 1.0.5'
--   Found gstreamer-pbutils-1.0 , version 1.12.3
-- Checking for module 'gstreamer-video-1.0 >= 1.0.5'
--   Found gstreamer-video-1.0 , version 1.12.3
-- Found GSTREAMER_1_0: /usr/lib64/libgstreamer-1.0.so  
-- Finding optional feature JPEG for codec (use JPEG library)
-- Found JPEG: /usr/lib/libjpeg.so  
-- Skipping optional feature x264 for codec (use x264 library)
--     Enable feature x264 using "-DWITH_X264=ON"
-- Finding optional feature OpenH264 for codec (use OpenH264 library)
-- Found OpenH264: /usr/lib/libopenh264.so  
-- Found OpenH264: /usr/lib/libopenh264.so
-- Skipping optional feature GSM for codec (GSM audio codec library)
--     Enable feature GSM using "-DWITH_GSM=ON"
-- Skipping optional feature GSSAPI for auth (add kerberos support)
--     Enable feature GSSAPI using "-DWITH_GSSAPI=ON"
-- Skipping optional feature IPP for performance (Intel Integrated Performance Primitives library)
--     Enable feature IPP using "-DWITH_IPP=ON"
-- Using OpenSSL Version: 1.0.2n
-- Looking for include file stdbool.h
-- Looking for include file stdbool.h - found
-- Looking for include file stdint.h
-- Looking for include file stdint.h - found
-- Looking for include file inttypes.h
-- Looking for include file inttypes.h - found
-- Finding recommended feature XKBFile for X11 keyboard (X11 keyboard file extension)
--     Disable feature XKBFile using "-DWITH_XKBFILE=OFF"
-- Found XKBFile: /usr/lib/libxkbfile.so  
-- Adding dynamic channel client server "audin": Audio Input Redirection Virtual Channel Extension
-- Adding static channel client server "cliprdr": Clipboard Virtual Channel Extension
-- Adding dynamic channel client "disp": Display Update Virtual Channel Extension
-- Adding static channel client server "drdynvc": Dynamic Virtual Channel Extension
-- Adding device channel client "drive": Drive Redirection Virtual Channel Extension
-- Adding dynamic channel client server "echo": Echo Virtual Channel Extension
-- Adding static channel client server "encomsp": Multiparty Virtual Channel Extension
-- Adding dynamic channel client "geometry": Geometry tracking Virtual Channel Extension
-- Adding device channel client "parallel": Parallel Port Virtual Channel Extension
-- Adding device channel client "printer": Print Virtual Channel Extension
-- Adding static channel client "rail": Remote Programs Virtual Channel Extension
-- Adding static channel client server "rdpdr": Device Redirection Virtual Channel Extension
-- Adding dynamic channel client "rdpei": Input Virtual Channel Extension
-- Adding dynamic channel client "rdpgfx": Graphics Pipeline Extension
-- Adding static channel client server "rdpsnd": Audio Output Virtual Channel Extension
-- Adding static channel client server "remdesk": Remote Assistance Virtual Channel Extension
-- Adding device channel client "serial": Serial Port Virtual Channel Extension
-- Adding device channel client "smartcard": Smart Card Virtual Channel Extension
-- Adding dynamic channel client "tsmf": Video Redirection Virtual Channel Extension
-- Finding required feature XRandR for X11 randr (X11 randr extension)
-- Found XRANDR: /usr/lib/libXrandr.so  
-- Finding recommended feature Xext for X11 extension (X11 core extensions)
--     Disable feature Xext using "-DWITH_XEXT=OFF"
-- Found Xext: /usr/lib/libXext.so  
-- Adding dynamic channel "urbdrc": USB Devices Virtual Channel Extension
-- libudev stable: 1
-- Found UDev: /usr/lib/libudev.so
--  include: /usr/include
-- Found UUID: /usr/lib/libuuid.so
-- Found dbus-glib: /usr/lib64/libdbus-glib-1.so  
-- Found libusb-1.0:
--  - Includes: /usr/include/libusb-1.0
--  - Libraries: /usr/lib/libusb-1.0.so
-- Found all URBDRC dependencies
-- Found DocBookXSL: /usr/share/sgml/docbook/xsl-stylesheets  
-- Finding required feature XShm for X11 shared memory (X11 shared memory extension)
-- Found XShm: /usr/lib/libXext.so  
-- Finding recommended feature Xinerama for multi-monitor (X11 multi-monitor extension)
--     Disable feature Xinerama using "-DWITH_XINERAMA=OFF"
-- Found Xinerama: /usr/lib/libXinerama.so  
-- Finding recommended feature Xext for X11 extension (X11 core extensions)
--     Disable feature Xext using "-DWITH_XEXT=OFF"
-- Finding recommended feature Xcursor for cursor (X11 cursor extension)
--     Disable feature Xcursor using "-DWITH_XCURSOR=OFF"
-- Found Xcursor: /usr/lib/libXcursor.so  
-- Finding recommended feature Xv for video (X11 video extension)
--     Disable feature Xv using "-DWITH_XV=OFF"
-- Found Xv: /usr/lib/libXv.so  
-- Finding recommended feature Xi for input (X11 input extension)
--     Disable feature Xi using "-DWITH_XI=OFF"
-- Found Xi: /usr/lib/libXi.so  
-- Looking for XITouchClass
-- Looking for XITouchClass - found
-- Finding recommended feature Xrender for rendering (X11 render extension)
--     Disable feature Xrender using "-DWITH_XRENDER=OFF"
-- Found Xrender: /usr/lib/libXrender.so  
-- Finding recommended feature XRandR for tracking output configuration (X11 randr extension)
--     Disable feature XRandR using "-DWITH_XRANDR=OFF"
-- Finding recommended feature Xfixes for X11 xfixes extension (Useful additions to the X11 core protocol)
--     Disable feature Xfixes using "-DWITH_XFIXES=OFF"
-- Found Xfixes: /usr/lib/libXfixes.so  
-- Finding recommended feature PAM for authentication (user authentication)
--     Disable feature PAM using "-DWITH_PAM=OFF"
-- Found PAM: /usr/lib/libpam.so;/usr/lib/libdl.so
-- Finding recommended feature Xext for X11 extension (X11 core extensions)
--     Disable feature Xext using "-DWITH_XEXT=OFF"
-- Finding recommended feature XShm for X11 shared memory (X11 shared memory extension)
--     Disable feature XShm using "-DWITH_XSHM=OFF"
-- Finding recommended feature XTest for X11 input event injection (X11 input event injection extension)
--     Disable feature XTest using "-DWITH_XTEST=OFF"
-- Found XTest: /usr/lib/libXtst.so  
-- Finding recommended feature Xfixes for X11 region (X11 region fix extension)
--     Disable feature Xfixes using "-DWITH_XFIXES=OFF"
-- Warning: Property DESCRIPTION for package Xfixes already set to "Useful additions to the X11 core protocol", overriding it with "X11 region fix extension"
-- Finding recommended feature Xdamage for X11 region damage (X11 region damage extension)
--     Disable feature Xdamage using "-DWITH_XDAMAGE=OFF"
-- Found Xdamage: /usr/lib/libXdamage.so  
-- Finding recommended feature Xinerama for multi-monitor (X11 multi-monitor extension)
--     Disable feature Xinerama using "-DWITH_XINERAMA=OFF"
-- Finding recommended feature XRandR for X11 resize, rotate and reflect (X11 resize, rotate and reflect extension)
--     Disable feature XRandR using "-DWITH_XRANDR=OFF"
-- Warning: Property DESCRIPTION for package XRandR already set to "X11 randr extension", overriding it with "X11 resize, rotate and reflect extension"
-- Finding recommended feature Xcursor for cursor (X11 cursor extension)
--     Disable feature Xcursor using "-DWITH_XCURSOR=OFF"
-- <<< Gentoo configuration >>>
Build type      Gentoo
Install path    /usr
Compiler flags:
C               -O2 -pipe -ggdb -rdynamic -fPIC -Wall -Wno-unused-result -Wno-unused-but-set-variable -Wno-deprecated-declarations -fvisibility=hidden -Wimplicit-function-declaration -Wredundant-decls -g
C++             -O2 -pipe -ggdb -rdynamic -Wno-deprecated-declarations -g
Linker flags:
Executable      -Wl,-O1 -Wl,--as-needed
Module          -Wl,-O1 -Wl,--as-needed
Shared          -Wl,-O1 -Wl,--as-needed

### PR DESCRIPTION
**Pull request by akallabeth**

### CODE REVIEW

File: winpr/libwinpr/sspi/NTLM/ntlm_compute.c [hunk 1]
```diff
@@ -281,6 +281,26 @@ int ntlm_convert_password_hash(NTLM_CONTEXT* context, BYTE* hash)
 int ntlm_compute_ntlm_v2_hash(NTLM_CONTEXT* context, BYTE* hash)
 {
 	SSPI_CREDENTIALS* credentials = context->credentials;
+#ifdef WITH_DEBUG_NTLM
+
+	if (credentials)
+	{
```
Comment (hardening) [inline winpr/libwinpr/sspi/NTLM/ntlm_compute.c]: How is it possible that credentials aren't set ?

Comment (akallabeth) [reply winpr/libwinpr/sspi/NTLM/ntlm_compute.c]: Added a debug message for that case.

Comment (hardening) [reply winpr/libwinpr/sspi/NTLM/ntlm_compute.c]: my question still applies, if the case ```context->credentials == NULL``` is totally unexpected, then this should be a ```assert(context->credentials)``` and we should not behave like ```NULL``` was a possible value for ```credentials```.

Comment (akallabeth) [reply winpr/libwinpr/sspi/NTLM/ntlm_compute.c]: this is an optional debug message block, so asserts are definitely wrong here.

Comment (hardening) [reply winpr/libwinpr/sspi/NTLM/ntlm_compute.c]: So you mean you take a special precaution to not crash in that debug statement, while we will segfault a few line later when using credentials without checks ?
So for me there's only two cases: 

* either ```credential != NULL``` is a precondition and we can possibly add  ```assert(credential != NULL)```, even if I'm almost sure we can't be in that situation because callers would have crashed long before; 
* or NULL is a possible value for credentials and we should add some checks even when debug is not enabled

I think we're in the first case.

Again, unneeded checks don't bring any security or program hardening.

Comment (akallabeth) [reply winpr/libwinpr/sspi/NTLM/ntlm_compute.c]: No, just that before any crash you actually have a debug message and don't need to launch a debugger for that.

Comment (hardening) [reply winpr/libwinpr/sspi/NTLM/ntlm_compute.c]: So I guess the assert is the solution...

Comment (akallabeth) [reply winpr/libwinpr/sspi/NTLM/ntlm_compute.c]: @hardening asserts are not compiled in release builds, so no that will not help.

**Comment by hardening** [comment]
@freerdp-bot can you test again ?
