### PR TITLE
Set file pointer fix

### LINKED ISSUE #4057: warning: #warning "FFMPEG does not support H264 encoding (GFX H264 server mode)
I compile for openSUSE Tumbleweed with:

-DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX:PATH=/usr -DCMAKE_INSTALL_LIBDIR:PATH=lib -DCMAKE_SKIP_INSTALL_RPATH=ON -DWITH_CUPS=ON -DWITH_CLIENT=ON -DWITH_PCSC=ON -DWITH_ALSA=ON -DWITH_PULSE=ON -DWITH_OSS=OFF -DWITH_DIRECTFB=OFF -DWITH_JPEG=ON -DWITH_GSM=ON -DWITH_GSTREAMER_1_0=ON -DWITH_IPP=OFF -DWITH_OPENSSL=ON -DWITH_CHANNELS=ON -DWITH_X11=ON -DWITH_XCURSOR=ON -DWITH_XEXT=ON -DWITH_XKBFILE=ON -DWITH_XI=ON -DWITH_XINERAMA=ON -DWITH_XRENDER=ON -DWITH_XV=ON -DWITH_ZLIB=ON -DWITH_KRB5=ON -DBUILTIN_CHANNELS=OFF -DWITH_SERVER=OFF -DWITH_SSE2=ON -DWITH_DEBUG_SCARD=OFF -DWITH_SMARTCARD_INSPECT=ON -DWITH_WAYLAND=ON -DWITH_LIBSYSTEMD=ON -DCMAKE_NO_BUILTIN_CHRPATH=ON 

Together with the available devel-libraries this results in:
-DWITH_FFMPEG=ON
-DWITH_X264=OFF
-DWITH_OPENH264=OFF 

Now I get this message:

[   55s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/libfreerdp/codec/h264_ffmpeg.c:29:2: warning: #warning "FFMPEG does not support H264 encoding (GFX H264 server mode). Please review your configuration!" [-Wcpp]
[   55s]  #warning "FFMPEG does not support H264 encoding (GFX H264 server mode). Please review your configuration!"
[   55s]   ^~~~~~~

Is this expected with above options?
For legal reasons the openSUSE packages do not support any patent encumbered codecs.

### LINKED ISSUE #4075: Copy more than 2g files
/drive:usb,/mnt/udisk/   Copy more than 2g files to u disk failed

freerdp Version :  https://github.com/FreeRDP/FreeRDP
Command line : xfreerdp -f /rfx /size:1920x1080 /drive:usb,/mnt/udisk/ /u:test5 /p:5 /v:192.168.1.124:3389 /bpp:16 /vc:rdpsnd,sys:alsa,dev:default,rate:44100,channel:2

when i copy files (the file size more than 2GB )from usb disk to server desktop , the client failed , and the file offset value is -2147483648

### PR DESCRIPTION
**Pull request by akallabeth**
Fixes #4075

### CODE REVIEW

**Comment by akallabeth** [comment]
@earcg Does it work for you as well?

File: winpr/libwinpr/file/file.c [hunk 1]
```diff
@@ -122,12 +122,19 @@ static DWORD FileSetFilePointer(HANDLE hFile, LONG lDistanceToMove,
...
 {
 	WINPR_FILE* pFile = (WINPR_FILE*) hFile;
-	long offset = lDistanceToMove;
+	INT64 offset;
 	int whence;
 
 	if (!hFile)
 		return INVALID_SET_FILE_POINTER;
 
+	if (lpDistanceToMoveHigh)
```
Comment (MartinHaimberger) [inline winpr/libwinpr/file/file.c]: nice catch
