### PR TITLE
Bugfix/blank screen

### LINKED ISSUE #5530: Server proxy - blank screen
When connecting to a server proxy, I get a blank screen.

**To Reproduce**
1. Build FreeRDP with WITH_SERVER=ON option
2. run freerdp-proxy with the config.ini file specifying a target
3. On a separate machine build FreeRDP
4. Run xfreerdp connecting to the proxy host, ensuring the keys in server/proxy/ folder are in your local folder
5. You will get a blank screen.

### PR DESCRIPTION
**Pull request by kubistika**
Fixes #5530.

Problem was that proxy's client was waiting for server's drynvc to be in ready state no matter if original client connected with any dynamic channel.

Fixed by: only waiting when needed. For disp, which doesn't have an early capability flag (like GFX) indicating that it will be opened, we first call Open and check if ERROR_NOT_FOUND was returned. If it wasn't the error, then we wait and call it again.

### CODE REVIEW

File: server/proxy/pf_channels.c [hunk 1]
```diff
@@ -68,13 +77,28 @@ void pf_OnChannelConnectedEventHandler(void* data,
 	}
 	else if (strcmp(e->name, DISP_DVC_CHANNEL_NAME) == 0)
 	{
-		if (ps->disp->Open(ps->disp) != CHANNEL_RC_OK)
```
Comment (akallabeth) [inline server/proxy/pf_channels.c]: Why this retry? I don't really understand your explanation, could you elaborate?

Comment (kubistika) [reply server/proxy/pf_channels.c]: yep.
first, i try to open disp. if it fails, i need to check if ERROR_NOT_FOUND is returned. it that's the case, then nothing should be done (client did not open disp). otherwise, it might not opened because server's dynvc wasn't in ready state yet. then, i wait for it to be in ready state and try again.

i must first check for ERROR_NOT_FOUND because drynvc will be in ready state only if a drdynvc caps sent from client.

File: server/proxy/pf_channels.c [hunk 2]
```diff
@@ -57,6 +64,8 @@ void pf_OnChannelConnectedEventHandler(void* data,
 	}
 	else if (strcmp(e->name, RDPGFX_DVC_CHANNEL_NAME) == 0)
 	{
+		pf_channels_wait_for_server_dynvc(ps);
```
Comment (akallabeth) [inline server/proxy/pf_channels.c]: Why not just wait on server `drdynvc` when the client `drdynvc` event is triggered?

Comment (kubistika) [reply server/proxy/pf_channels.c]: Because client drdynvc event will be triggered even if original client did not connect with any dynamic channel. This is because proxy's client always opens DISP, because it has no idea whether if original client connected with disp or not.

Comment (kubistika) [reply server/proxy/pf_channels.c]: @akallabeth

Comment (akallabeth) [reply server/proxy/pf_channels.c]: @kubistika sorry, did want to think a bit about it, but did not have time.
lets merge this one and (hopefully) come up with a better solution later.

Comment (kubistika) [reply server/proxy/pf_channels.c]: I'd really appreciate if you will have the time to help me figure another solution. I don't like it too but this is the only solution I found for this :/ (that makes sure channels will be opened)

Comment (akallabeth) [reply server/proxy/pf_channels.c]: I'll keep an eye open for this, but currently a bit busy :/
