### PR TITLE
Fix proxy config

### LINKED ISSUE #5848: proxy default config.ini incompatible
**Describe the bug**
This change to not compile demo modules for the proxy causes the current default config.ini to cause an error:
https://github.com/FreeRDP/FreeRDP/commit/e3728c1822f041f9d8725afae93b481dcd491155

Error caused by Required Plugin statement:
https://github.com/FreeRDP/FreeRDP/blob/master/server/proxy/config.ini#L44

**To Reproduce**
1. compile with:
`cmake -GNinja -DCHANNEL_URBDRC=ON -DWITH_DSP_FFMPEG=ON -DWITH_CUPS=ON -DWITH_PULSE=ON -DWITH_FAAC=ON -DWITH_FAAD2=ON -DWITH_GSM=ON -DWITH_SERVER=on`
2. start freerdp-proxy
3. See error:
```
[12:51:43:891] [48322:48322] [ERROR][proxy.modules] - FindFirstFile failed!
[12:51:43:891] [48322:48322] [ERROR][proxy.server] - failed to initialize proxy plugins!
```

**Expected behavior**
freerdp-proxy should be able to start with default config.ini

** Application details
* Version of FreeRDP
`git log
commit 706e32982ecafce069d34c8b2015caac0bb3038d (HEAD -> master, origin/master, origin/HEAD)
`

* Command line used

* output of `/buildconfig`
`xfreerdp /buildconfig
[12:48:30:508] [48299:48299] [ERROR][com.freerdp.client.x11] - failed to open display:
[12:48:30:508] [48299:48299] [ERROR][com.freerdp.client.x11] - Please check that the $DISPLAY environment variable is properly set.
`

**Desktop (please complete the following information):**
 - OS: 
`.4.0-9-generic #12-Ubuntu SMP Mon Dec 16 22:34:19 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu Focal Fossa (development branch)"
`

### PR DESCRIPTION
**Pull request by kubistika**
Fixes #5848

### CODE REVIEW

File: server/proxy/pf_modules.c [hunk 1]
```diff
@@ -319,8 +319,19 @@ BOOL pf_modules_init(const char* modules_directory)
...
+			WLog_ERR(TAG, "error occurred while creating modules directory: %s", modules_directory);
+			return FALSE;
+		}
+
+		return TRUE;
+	}
+
 	WLog_DBG(TAG, "searching plugins in directory %s", modules_directory);
-	find_path = GetCombinedPath(modules_directory, "*");
+	find_path = GetCombinedPath(modules_directory, "*.so");
```
Comment (akallabeth) [inline server/proxy/pf_modules.c]: sure you only want `.so` files?

Comment (kubistika) [reply server/proxy/pf_modules.c]: For now, yes, doesn't really matters
