### PR TITLE
Fix #5121: Determine actual string length for input data

### LINKED ISSUE #5121: Failure to get clipboard data when copying Windows Update info
Local Host: Gentoo x86_64 with X
Tested Remote Hosts: Windows 7, Windows 8, Windows Server 2008 R2, and Windows Server 2012
FreeRDP: Version: 2.0.0_rc2, 2.0.0_rc4, latest master: https://github.com/FreeRDP/FreeRDP/commit/fc12b9336f6c6b5b49bdfc564ce8e4443d9e82ef

To reproduce: Go to "Control Panel\All Control Panel Items\Windows Update" in Windows Explorer then after clicking on an update to get to "Control Panel\All Control Panel Items\Windows Update\Select updates to install", right-click on the text under the Name column and click "Copy details"

Command Line: xfreerdp /u:user /p:pwd

freerdp exits with message:
[17:34:01:151] [9552:9595] [ERROR][com.freerdp.client.x11] - failed to get clipboard data in format UTF8_STRING [source format CF_UNICODETEXT]
[17:34:01:151] [9552:9595] [ERROR][com.freerdp.channels.cliprdr.client] - ServerFormatDataResponse failed with error 1359!
[17:34:01:151] [9552:9595] [ERROR][com.freerdp.channels.cliprdr.client] - cliprdr_process_format_data_response failed with error 1359!
[17:34:01:151] [9552:9595] [ERROR][com.freerdp.channels.cliprdr.client] - cliprdr_order_recv failed with error 1359!
[17:34:01:151] [9552:9553] [ERROR][com.freerdp.core] - cliprdr_virtual_channel_client_thread reported an error. Error was 1359

### PR DESCRIPTION
**Pull request by akallabeth**
ConvertFromUnicode ignores '\0' sequences when the length of the input
string is given. Clipboard strings may be larger than the actual string
length and padded with random data leading to decoding errors.
Limit the length to the first occurrence of a '\0'.

### CODE REVIEW

**Comment by akallabeth** [comment]
@freerdp-bot test

File: winpr/include/winpr/string.h [hunk 1]
```diff
@@ -58,6 +58,8 @@ WINPR_API int _strnicmp(const char* string1, const char* string2, size_t count);
 WINPR_API int _wcscmp(const WCHAR* string1, const WCHAR* string2);
 
 WINPR_API size_t _wcslen(const WCHAR* str);
+WINPR_API size_t _wcsnlen(const WCHAR* str, size_t numberOfElements);
```
Comment (bmiklautz) [inline winpr/include/winpr/string.h]: Would possibly be a good idea to indicat that numberOfElements is the maximum number.
