### PR TITLE
[WIN] Added additional mouse mappings.

### LINKED ISSUE #4442: wfreerdp: mouse scrollwheel click does not work
Scrollwheel click does not appear to be captured. I typically use it for closing tabs and opening links in new tabs.
Scrollwheel up and down works correctly.

Host OS: Windows POSReady 2009(XP SP3 derivate) x86
Host RDP protocol supported: v7.0
Client OS: Windows 8 x86
Command used: wfreerdp profile.rdp /v:address:port /gdi:sw
Profile used: https://pastebin.com/60cNrpLd
Free RDP version: https://ci.freerdp.com/job/freerdp-nightly-windows/ win32, nr446

### PR DESCRIPTION
**Pull request by akallabeth**
Added missing mouse buttons (Fixes #4442)
* Horizontal wheel support
* extended button support
* middle mouse button support

### CODE REVIEW

File: client/Windows/wf_event.c [hunk 1]
```diff
@@ -656,13 +696,18 @@ BOOL wf_scale_blt(wfContext* wfc, HDC hdc, int x, int y, int w, int h,
...
+static BOOL wf_scale_mouse_pos(wfContext* wfc, UINT16* x, UINT16* y)
 {
 	int ww, wh, dw, dh;
 	rdpContext* context;
-	rdpSettings* settings = wfc->context.settings;
-	MouseEventEventArgs eventArgs;
+	rdpSettings* settings;
+       
+	if (!wfc || !x || !y)
+		return FALSE;
```
Comment (hardening) [inline client/Windows/wf_event.c]: unneeded checks these should be asserts

Comment (akallabeth) [reply client/Windows/wf_event.c]: @hardening API checks, this is not internal (client != lib)

Comment (hardening) [reply client/Windows/wf_event.c]: This is a local functions, just give me the case where one of these pointers could be NULL and you'll see that it implies that a caller didn't do the check job.
