### PR TITLE
Fix #4524: Initialize with cleanup handler

### LINKED ISSUE #4524: Commit 7e26c548668508ca59b5b204b4973d2a4ef8d4ce causes crash in multi-client service.
freerdp crashes on logging calls, because  WLog_Uninit() calls WLog_Free(root) while other thread is in the middle of WLog* call.
Suggest removing WLog_Uninit() (WLog_Init() seems harmless)

### PR DESCRIPTION
**Pull request by akallabeth**
Use singleton initializer and register cleanup handler for logger.

manually cleaning up WLog by calling `WLog_Uninit` is not really feasable, do it at program termination.

### CODE REVIEW

File: winpr/libwinpr/utils/wlog/wlog.c [hunk 1]
```diff
@@ -66,12 +66,103 @@ LPCSTR WLOG_LEVELS[7] =
...
+
+static BOOL CALLBACK WLog_InitializeRoot(PINIT_ONCE InitOnce, PVOID Parameter, PVOID* Context)
+{
+	char* env;
+	DWORD nSize;
+	DWORD logAppenderType;
+
+	if (!g_RootLog)
+	{
+		LPCSTR appender = "WLOG_APPENDER";
```
Comment (hardening) [inline winpr/libwinpr/utils/wlog/wlog.c]: AFAICT when this function is called g_RootLog is always NULL, so the `if(!g_RootLog)` test is useless.

Comment (akallabeth) [reply winpr/libwinpr/utils/wlog/wlog.c]: @hardening right, classic copy paste error ^^

**Comment by akallabeth** [comment]
@freerdp-bot test please

File: winpr/libwinpr/utils/wlog/wlog.c [hunk 2]
```diff
@@ -66,12 +66,99 @@ LPCSTR WLOG_LEVELS[7] =
...
+		else if (_stricmp(env, "UDP") == 0)
+			logAppenderType = WLOG_APPENDER_UDP;
+
+		free(env);
+	}
+
+	if (!WLog_SetLogAppenderType(g_RootLog, logAppenderType))
+		goto fail;
+
+	atexit(WLog_Uninit_);
```
Comment (mfleisz) [inline winpr/libwinpr/utils/wlog/wlog.c]: I think this could get us into trouble. MSDN says:

"The code in the atexit function should not contain any dependency on any DLL which could have already been unloaded when the atexit function is called."

If someone uses a custom logger with cleanup code like i.e. WLog_UdpAdapter_Free (which calls socket APIs) this could lead to crashes on app exit.

Not sure what you guys think about this - maybe I'm just too pessimistic here ... ^^

Comment (akallabeth) [reply winpr/libwinpr/utils/wlog/wlog.c]: @mfleisz That would also crash if `WLog_*` functions are called...
Don't think that the dependent libs are already unloaded there (unless someone really wants to get hurt)

Comment (mfleisz) [reply winpr/libwinpr/utils/wlog/wlog.c]: @akallabeth WLog_* functions won't be a problem as they are part of winpr.dll and are still loaded when the atexit() handler is called (on dll unload of winpr). There is just no guarantee the adapter free handlers won't call any functions from other dlls that might have been already unloaded before winpr.

Comment (akallabeth) [reply winpr/libwinpr/utils/wlog/wlog.c]: @mfleisz My understanding of this is that it is only relevant when using `WinPR` with `dlopen`/`dlclose` (or `LoadLibrary`/`CloseHandle`)
