### PR TITLE
Rdp file preference fix

### LINKED ISSUE #2810: option /cert-ignore not working anymore
On today master, the option /cert-ignore seems to not be applied, the mismatche certificate is always prompted to be accepted or refused...

### PR DESCRIPTION
**Pull request by akallabeth**
* Fixes #2810, #3199 

When using a RDP or assistance file the command line was overwritten by the values from the file.
This pull fixes that by reparsing the command line and replacing the defaults set by the file parser with the command line values.

### CODE REVIEW

File: client/common/cmdline.c [hunk 1]
```diff
@@ -1474,6 +1474,7 @@ int freerdp_client_settings_parse_command_line_arguments(rdpSettings* settings,
 
 				CommandLineSwitchCase(arg, "v")
 		{
+			free (settings->ServerHostname);
```
Comment (mfleisz) [inline client/common/cmdline.c]: settings->ServerHostname should be NULLed here or we might end up with a double free in case strchr below fails

File: client/common/cmdline.c [hunk 2]
```diff
@@ -1715,16 +1721,19 @@ int freerdp_client_settings_parse_command_line_arguments(rdpSettings* settings,
...
 		}
 		CommandLineSwitchCase(arg, "p")
 		{
+			free (settings->Password);
 			if (!(settings->Password = _strdup(arg->Value)))
 				return COMMAND_LINE_ERROR_MEMORY;
 		}
 		CommandLineSwitchCase(arg, "g")
 		{
+			free (settings->GatewayHostname);
```
Comment (mfleisz) [inline client/common/cmdline.c]: settings->GatewayHostname should be NULLed (possible double free later on)

**Comment by mfleisz** [comment]
Except my remark +1

**Comment by bmiklautz** [comment]
@akallabeth just tested this looks like overriding doesn't work (at least with passwords).
Tested with:
```
xfreerdp test.rdp /p:verysecret
```

**Comment by akallabeth** [comment]
@freerdp-bot test

**Comment by bmiklautz** [comment]
With your last commit it works nicely.
