### PR TITLE
Fixed VirtualChannelWriteEx error case leaks.

### LINKED ISSUE #4809: 3rd party virtual channels cause "double free or corruption"
We integrate different 3rd party virtual channel drivers. They worked fine with rc2, but cause "double free or curruption" crashes with rc3. Connecting to the server works, but immediately after initializing the channel freerdp crashes with:
`*** Error in `/opt/freerdp-nightly/bin/xfreerdp': double free or corruption (fasttop): 0xf07011b8 ***`

Bisection lead to the following commit:

```
328eba7fe95c7616e2c97afec3dd4a6eb4b86e26 is the first bad commit
commit 328eba7fe95c7616e2c97afec3dd4a6eb4b86e26
Author: Armin Novak <armin.novak@thincast.com>
Date:   Wed Jul 18 15:16:50 2018 +0200

    Fix #4752: Provide message free function for channel queue.

:040000 040000 6a0f65e563cce77a059450dbe54ac7bc49e69700 6afb0cec5667e9aef1631d75b211bb0ff15be478 M	client
:040000 040000 32cad6825827530a436ca31d389d74a3749fe690 d1e5a8f0f51a022b8def47f3976c3063f11dd323 M	libfreerdp
bisect run success
```

Multiple virtual channel drivers are affected. If you require any further information, let me know.

Thank you!

### PR DESCRIPTION
**Pull request by akallabeth**
* Missing buffer free in error tree fixed.
* Fix #4809: Since this one has been open quite some time (and was previously misinterpreted by me) I´d like to wait for some feedback from plugin devs before this is merged.
(the api is modeled after https://docs.microsoft.com/en-us/windows/win32/api/cchannel/nc-cchannel-virtualchannelwrite )

### CODE REVIEW

File: channels/remdesk/client/remdesk_main.c [hunk 1]
```diff
@@ -795,6 +786,10 @@ static VOID VCAPITYPE remdesk_virtual_channel_open_event_ex(LPVOID lpUserParam,
 			break;
 
 		case CHANNEL_EVENT_WRITE_COMPLETE:
+		{
```
Comment (mfleisz) [inline channels/remdesk/client/remdesk_main.c]: Should handle `CHANNEL_EVENT_WRITE_CANCELLED` too

Comment (akallabeth) [reply channels/remdesk/client/remdesk_main.c]: done

**Comment by metametaclass** [comment]
I`ve tested our plugin with merged PR, there are no more segfaults in buffer cleanup code. 

But when testing I have found another issue - strnlen calls with NULL arguments in plugin loading code, which are UB: 

==6299==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x7fcf7a586900 bp 0x7fcf684c90e0 sp 0x7fcf684c8868 T1)
    #0 0x7fcf7a5868ff in strnlen (/lib/x86_64-linux-gnu/libc.so.6+0x8b8ff)
    #1 0x7fcf7d03043b in __interceptor_strnlen (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x5043b)
    #2 0x7fcf7b2de763 in freerdp_load_dynamic_channel_addin_entry /home/user/FreeRDP/libfreerdp/common/addin.c:245
    #3 0x7fcf7b2de8d8 in freerdp_load_channel_addin_entry /home/user/FreeRDP/libfreerdp/common/addin.c:350
    #4 0x7fcf7b87d6f7 in freerdp_client_load_static_channel_addin /home/user/FreeRDP/client/common/cmdline.c:3207
    #5 0x7fcf7b88a285 in freerdp_client_load_addins /home/user/FreeRDP/client/common/cmdline.c:3481
    #6 0x445930 in xf_pre_connect /home/user/FreeRDP/client/X11/xf_client.c:1164
    #7 0x7fcf7b3b05f5 in freerdp_connect /home/user/FreeRDP/libfreerdp/core/freerdp.c:176
    #8 0x44957d in xf_client_thread /home/user/FreeRDP/client/X11/xf_client.c:1503
    #9 0x7fcf7a9e372e in thread_launcher /home/user/FreeRDP/winpr/libwinpr/thread/thread.c:334
    #10 0x7fcf7a2e56b9 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x76b9)
    #11 0x7fcf7a60241c in clone (/lib/x86_64-linux-gnu/libc.so.6+0x10741c)

I fixed them for testing, should I make a PR?:
https://github.com/metametaclass/FreeRDP/commit/0279399031599f6631733b2a16dd24ccd573cf97

**Comment by akallabeth** [comment]
@metametaclass thanks for the quick feedback. Fixed it and pushed a commit to #5703
