### PR TITLE
Fixed hotplug mount locations.

### LINKED ISSUE #3909: Hard coded automount paths for disk redirection
#3864 introduced better disk redirection support (naming, ...) but introduced a hard coded ```/media``` check. This path is more or less ubuntu only. @DavBfr Could you have a look at the ```udisks2``` documentation to get the proper path for the distribution used?

### PR DESCRIPTION
**Pull request by akallabeth**
Fixes #3909

### CODE REVIEW

File: channels/rdpdr/client/rdpdr_main.c [hunk 1]
```diff
@@ -72,9 +72,49 @@ typedef struct _DEVICE_DRIVE_EXT DEVICE_DRIVE_EXT;
...
 	DEVICE device;
-	char* path;
+	WCHAR* path;
+};
+
+static const char* automountLocations[] =
+{
+	"/run/user/%lu/gvfs",
+	"/run/media/%s",
+	"/media/%s",
```
Comment (DavBfr) [inline channels/rdpdr/client/rdpdr_main.c]: It also been in /media for old releases of ubuntu/debian

File: channels/rdpdr/client/rdpdr_main.c [hunk 2]
```diff
@@ -72,9 +72,49 @@ typedef struct _DEVICE_DRIVE_EXT DEVICE_DRIVE_EXT;
...
+		size_t length;
+
+		if (strstr(location, "%lu"))
+			snprintf(buffer, sizeof(buffer), location, (unsigned long)uid);
+		else if (strstr(location, "%s"))
+			snprintf(buffer, sizeof(buffer), location, uname);
+		else
+			snprintf(buffer, sizeof(buffer), "%s", location);
+
+		length = strnlen(buffer, MAX_PATH);
```
Comment (DavBfr) [inline channels/rdpdr/client/rdpdr_main.c]: Why not use sizeof(buffer) too here?

**Comment by akallabeth** [comment]
@DavBfr Ok, found a memory corruption, best you run your changes with active address sanitizer before creating a new pull next time. (CMake option ```-DWITH_SANITIZE_ADDRESS=ON``` and ```-DWITH_SANITIZE_LEAK=ON``` for leaks)
