### PR TITLE
fix #6788  libfreerdp: core: deep copy ServerCertificate

### LINKED ISSUE #6788: *** Error in `./freerdp-proxy': double free or corruption (out): 0x00007f63a801bb60 ***
build option:
cmake -DCMAKE_BUILD_TYPE=Debug -DWITH_SERVER=ON -DWITH_PROXY=ON -DWITH_PROXY_MODULES=ON .

config.ini:

[Security]
ServerTlsSecurity = TRUE
ServerRdpSecurity = FALSE
ClientTlsSecurity = FALSE
ClientRdpSecurity = TRUE
ClientNlaSecurity = TRUE
ClientAllowFallbackToTls = TRUE

**Describe the bug**
 settings->ServerCertificate maybe double free

==177270== Invalid free() / delete / delete[] / realloc()
==177270==    at 0x4C28FBD: free (vg_replace_malloc.c:540)
==177270==    by 0x56DEC5B: freerdp_settings_free_internal (in /usr/local/lib64/libfreerdp3.so.3.0.0)
==177270==    by 0x56DEED5: freerdp_settings_free (in /usr/local/lib64/libfreerdp3.so.3.0.0)
==177270==    by 0x5707889: rdp_free (in /usr/local/lib64/libfreerdp3.so.3.0.0)
==177270==    by 0x5728957: freerdp_peer_context_free (in /usr/local/lib64/libfreerdp3.so.3.0.0)
==177270==    by 0x40B50B: pf_server_handle_peer (in /usr/local/bin/freerdp-proxy)
==177270==    by 0x53AEA96: thread_launcher (in /usr/local/lib64/libwinpr3.so.3.0.0)
==177270==    by 0x5FD2DC4: start_thread (in /usr/lib64/libpthread-2.17.so)
==177270==    by 0x5AFC74C: clone (in /usr/lib64/libc-2.17.so)

==177270==  Address 0x9a89e70 is 0 bytes inside a block of size 376 free'd
==177270==    at 0x4C28FBD: free (vg_replace_malloc.c:540)
==177270==    by 0x570774C: rdp_reset (in /usr/local/lib64/libfreerdp3.so.3.0.0)
==177270==    by 0x56FC4EF: rdp_client_disconnect (in /usr/local/lib64/libfreerdp3.so.3.0.0)
==177270==    by 0x56EE8B6: freerdp_disconnect (in /usr/local/lib64/libfreerdp3.so.3.0.0)
==177270==    by 0x406357: pf_client_thread_proc (in /usr/local/bin/freerdp-proxy)
==177270==    by 0x53AEA96: thread_launcher (in /usr/local/lib64/libwinpr3.so.3.0.0)
==177270==    by 0x5FD2DC4: start_thread (in /usr/lib64/libpthread-2.17.so)
==177270==    by 0x5AFC74C: clone (in /usr/lib64/libc-2.17.so)

==177270==  Block was alloc'd at
==177270==    at 0x4C27EC3: malloc (vg_replace_malloc.c:309)
==177270==    by 0x56C6586: gcc_read_conference_create_response (in /usr/local/lib64/libfreerdp3.so.3.0.0)
==177270==    by 0x56C93D3: mcs_recv_connect_response (in /usr/local/lib64/libfreerdp3.so.3.0.0)
==177270==    by 0x57068E3: rdp_recv_callback (in /usr/local/lib64/libfreerdp3.so.3.0.0)
==177270==    by 0x571174E: transport_check_fds (in /usr/local/lib64/libfreerdp3.so.3.0.0)
==177270==    by 0x5707509: rdp_check_fds (in /usr/local/lib64/libfreerdp3.so.3.0.0)
==177270==    by 0x56FC2C5: rdp_client_connect (in /usr/local/lib64/libfreerdp3.so.3.0.0)
==177270==    by 0x56EFADF: freerdp_connect (in /usr/local/lib64/libfreerdp3.so.3.0.0)
==177270==    by 0x40644A: pf_client_thread_proc (in /usr/local/bin/freerdp-proxy)
==177270==    by 0x53AEA96: thread_launcher (in /usr/local/lib64/libwinpr3.so.3.0.0)
==177270==    by 0x5FD2DC4: start_thread (in /usr/lib64/libpthread-2.17.so)
==177270==    by 0x5AFC74C: clone (in /usr/lib64/libc-2.17.so)
==177270== 

gdb info:
(gdb) bt
#0  0x00007fe49b90e1d7 in raise () from /lib64/libc.so.6
#1  0x00007fe49b90f8c8 in abort () from /lib64/libc.so.6
#2  0x00007fe49b94df07 in __libc_message () from /lib64/libc.so.6
#3  0x00007fe49b955503 in _int_free () from /lib64/libc.so.6
#4  0x00007fe49bd25816 in freerdp_settings_free_internal (settings=0x7fe4880008c0) at /data/FreeRDP/libfreerdp/core/settings.c:624
#5  0x00007fe49bd2598f in freerdp_settings_free (settings=0x7fe4880008c0) at /data/FreeRDP/libfreerdp/core/settings.c:657
#6  0x00007fe49bd55c91 in rdp_free (rdp=0x7fe48800d4b0) at /data/FreeRDP/libfreerdp/core/rdp.c:1961
#7  0x00007fe49bd7af20 in freerdp_peer_context_free (client=0x7fe4900008c0) at /data/FreeRDP/libfreerdp/core/peer.c:860
#8  0x000000000040f6a0 in pf_server_handle_peer (arg=0x7fe4900008c0) at /data/FreeRDP/server/proxy/pf_server.c:478
#9  0x00007fe49c1098ea in thread_launcher (arg=0x7fe490000a70) at /data/FreeRDP/winpr/libwinpr/thread/thread.c:327
#10 0x00007fe49b4c0dc5 in start_thread () from /lib64/libpthread.so.0
#11 0x00007fe49b9d074d in clone () from /lib64/libc.so.6

### PR DESCRIPTION
**Pull request by merlin82**

### CODE REVIEW

**Review by hardening — APPROVED** [review]
LGTM

**Comment by hardening** [comment]
@freerdp-bot can you test that please ?
@merlin82 next time please remove the PR text as asked, thank you.

File: libfreerdp/core/settings.c [hunk 1]
```diff
@@ -701,6 +701,17 @@ static BOOL freerdp_settings_int_buffer_copy(rdpSettings* _settings, const rdpSe
...
 	}
 
+	if (settings->ServerCertificateLength)
+	{
+		_settings->ServerCertificate = (BYTE*)malloc(settings->ServerCertificateLength);
+
+		if (!_settings->ServerCertificate)
+			goto out_fail;
+
+		CopyMemory(_settings->ServerCertificate, settings->ServerCertificate, _settings->ServerCertificateLength);
```
Comment (akallabeth) [inline libfreerdp/core/settings.c:711]: This looks like a bug, surely you meant `settings->ServerCertificateLength` here? because you copy it only in the next line.

**Review by akallabeth — CHANGES_REQUESTED** [review]

**Comment by akallabeth** [comment]
@merlin82 please also run `clang-format` on your code changes (or check the link in the pull request tester, there is a diff of what is not as expected in the log)

**Comment by akallabeth** [comment]
@merlin82 ok, did push the required changes to your branch, thank you for this fix!

**Review by akallabeth — APPROVED** [review]

**Comment by akallabeth** [comment]
@freerdp-bot test
