### PR TITLE
Fixed #4249: Corruption due to recursive parser

### LINKED ISSUE #4249: Long Path for /drive Causing Parameter Corruption
If the path for /drive is too long, it seems to be corrupting the hostname for certificate matching. For example:

xfreerdp 5-B400DC003.rdp /drive:Remote,/home/KHolloway/xxxxxxx

works fine. However, adding one more character to the path:

xfreerdp 5-B400DC003.rdp /drive:Remote,/home/KHolloway/xxxxxxxx

causes a certificate name mismatch warning:

[10:49:34:726] [30755:30756] [INFO][com.freerdp.client.common.cmdline] - loading channelEx rdpdr
[10:49:34:726] [30755:30756] [INFO][com.freerdp.client.common.cmdline] - loading channelEx rdpsnd
[10:49:34:726] [30755:30756] [INFO][com.freerdp.client.common.cmdline] - loading channelEx cliprdr
[10:49:34:868] [30755:30756] [ERROR][com.freerdp.crypto] - @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[10:49:34:868] [30755:30756] [ERROR][com.freerdp.crypto] - @           WARNING: CERTIFICATE NAME MISMATCH!           @
[10:49:34:868] [30755:30756] [ERROR][com.freerdp.crypto] - @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[10:49:34:868] [30755:30756] [ERROR][com.freerdp.crypto] - The hostname used for this connection (oway/xxxxxxxx:3389) 
[10:49:34:868] [30755:30756] [ERROR][com.freerdp.crypto] - does not match any of the names given in the certificate:
[10:49:34:868] [30755:30756] [ERROR][com.freerdp.crypto] - Common Name (CN):
[10:49:34:868] [30755:30756] [ERROR][com.freerdp.crypto] -      host.domain.com
[10:49:34:868] [30755:30756] [ERROR][com.freerdp.crypto] - Alternative names:
[10:49:34:868] [30755:30756] [ERROR][com.freerdp.crypto] -       host.domain.com
[10:49:34:868] [30755:30756] [ERROR][com.freerdp.crypto] -       www.host.domain.com
[10:49:34:868] [30755:30756] [ERROR][com.freerdp.crypto] - A valid certificate for the wrong name should NOT be trusted!

### PR DESCRIPTION
**Pull request by akallabeth**
Due to command line parser utilizing the global ```args``` struct as temporary storage the recursive calles when using ```.rdp``` or ```.msrcIncident``` file parsing could cause memory corruptions.
This pull eliminates that by parsing those files before parsing the command line.

### CODE REVIEW

File: client/common/cmdline.c [hunk 1]
```diff
@@ -1489,13 +1480,31 @@ int freerdp_client_settings_parse_command_line_arguments(rdpSettings* settings,
...
 			flags |= COMMAND_LINE_IGN_UNKNOWN_KEYWORD;
 		}
 
+		if (argc > 1)
+		{
+			const char* ext = strstr(argv[1], ".rdp");
+			const char* assist = strstr(argv[1], ".msrcIncident");
+
+			if (ext)
+			{
```
Comment (hardening) [inline client/common/cmdline.c]: Perhaps we should check that it is ending by .rdp, than just checking that the filename contains .str

**Comment by akallabeth** [comment]
@freerdp-bot test
