### PR TITLE
[leak fixes] Refactored order updates

### LINKED ISSUE #4518: multiple issues with order memory handling
Dynamic memory handling in `orders.c`, `update.c` and `message.c` is broken:
* Some orders have variable length buffers (e.g. CACHE_GLYPH and others)
  * In `update_recv_secondary_order` or `update_recv_altsec_order` or `update_recv_primary_order` no copy of the data must be created
  * Only when using `async-update` copies of said buffers must be created in the callback function in `message.c`
  * `update_message_free_class` needs to be updated and checked to free all resources previously allocated
  * Client implementations of callbacks from the order read functions must create a copy of data they want to persist

Some Orders have already proper checks, but overall the handling must be unified

### PR DESCRIPTION
**Pull request by akallabeth**
* Unified order creation/copy/delete to avoid memory leaks.
* Added (a lot of) return value checks
Fixes #4518

### CODE REVIEW

File: libfreerdp/core/update.c [hunk 1]
```diff
@@ -427,37 +466,74 @@ BOOL update_read_pointer_color(wStream* s, POINTER_COLOR_UPDATE* pointer_color,
...
 	if ((pointer_new->xorBpp < 1) || (pointer_new->xorBpp > 32))
 	{
 		WLog_ERR(TAG,  "invalid xorBpp %"PRIu32"", pointer_new->xorBpp);
-		return FALSE;
+		goto fail;
 	}
 
-	return update_read_pointer_color(s, &pointer_new->colorPtrAttr,
-	                                 pointer_new->xorBpp); /* colorPtrAttr */
+	if (!_update_read_pointer_color(s, &pointer_new->colorPtrAttr,
```
Comment (mfleisz) [inline libfreerdp/core/update.c]: Should be `_update_read_pointer_new`

File: libfreerdp/core/update.c [hunk 2]
```diff
@@ -524,52 +626,65 @@ BOOL update_recv(rdpUpdate* update, wStream* s)
...
+				BITMAP_UPDATE* bitmap_update = update_read_bitmap_update(update, s);
+
+				if (!bitmap_update)
+				{
+					WLog_ERR(TAG, "UPDATE_TYPE_BITMAP - update_read_bitmap_update() failed");
+					return FALSE;
+				}
 
-			IFCALL(update->BitmapUpdate, context, &update->bitmap_update);
+				rc = IFCALLRESULT(FALSE, update->BitmapUpdate, context, &update->bitmap_update);
```
Comment (mfleisz) [inline libfreerdp/core/update.c]: Should be `bitmap_update` instead of `&update->bitmap_update`

File: libfreerdp/cache/glyph.c [hunk 3]
```diff
@@ -762,3 +764,120 @@ void glyph_cache_free(rdpGlyphCache* glyphCache)
...
+			if (!data->aj)
+				goto fail;
+
+			memcpy(data->aj, src->aj, size);
+		}
+	}
+
+	if (glyph->unicodeCharacters)
+	{
+		dst->unicodeCharacters = calloc(glyph->cGlyphs, sizeof(WCHAR));
```
Comment (mfleisz) [inline libfreerdp/cache/glyph.c]: `malloc` suffices here

File: libfreerdp/cache/glyph.c [hunk 4]
```diff
@@ -762,3 +764,120 @@ void glyph_cache_free(rdpGlyphCache* glyphCache)
...
```
Comment (mfleisz) [inline libfreerdp/cache/glyph.c]: `malloc` suffices here

File: libfreerdp/cache/pointer.c [hunk 5]
```diff
@@ -312,3 +313,156 @@ void pointer_cache_free(rdpPointerCache* pointer_cache)
...
+	POINTER_COLOR_UPDATE* dst = calloc(1, sizeof(POINTER_COLOR_UPDATE));
+
+	if (!dst || !src)
+		goto fail;
+
+	*dst = *src;
+
+	if (src->lengthAndMask > 0)
+	{
+		dst->andMaskData = calloc(src->lengthAndMask, sizeof(BYTE));
```
Comment (mfleisz) [inline libfreerdp/cache/pointer.c]: `malloc` suffices here

File: libfreerdp/cache/pointer.c [hunk 6]
```diff
@@ -312,3 +313,156 @@ void pointer_cache_free(rdpPointerCache* pointer_cache)
...
+
+		if (!dst->andMaskData)
+			goto fail;
+
+		memcpy(dst->andMaskData, src->andMaskData, src->lengthAndMask);
+	}
+
+	if (src->lengthXorMask > 0)
+	{
+		dst->xorMaskData = calloc(src->lengthXorMask, sizeof(BYTE));
```
Comment (mfleisz) [inline libfreerdp/cache/pointer.c]: `malloc` suffices here

File: libfreerdp/cache/pointer.c [hunk 7]
```diff
@@ -312,3 +313,156 @@ void pointer_cache_free(rdpPointerCache* pointer_cache)
...
+	POINTER_NEW_UPDATE* dst = calloc(1, sizeof(POINTER_NEW_UPDATE));
+
+	if (!dst || !src)
+		goto fail;
+
+	*dst = *src;
+
+	if (src->colorPtrAttr.lengthAndMask > 0)
+	{
+		dst->colorPtrAttr.andMaskData = calloc(src->colorPtrAttr.lengthAndMask, sizeof(BYTE));
```
Comment (mfleisz) [inline libfreerdp/cache/pointer.c]: `malloc` suffices here

File: libfreerdp/cache/pointer.c [hunk 8]
```diff
@@ -312,3 +313,156 @@ void pointer_cache_free(rdpPointerCache* pointer_cache)
...
+		if (!dst->colorPtrAttr.andMaskData)
+			goto fail;
+
+		memcpy(dst->colorPtrAttr.andMaskData, src->colorPtrAttr.andMaskData,
+		       src->colorPtrAttr.lengthAndMask);
+	}
+
+	if (src->colorPtrAttr.lengthXorMask > 0)
+	{
+		dst->colorPtrAttr.xorMaskData = calloc(src->colorPtrAttr.lengthXorMask, sizeof(BYTE));
```
Comment (mfleisz) [inline libfreerdp/cache/pointer.c]: `malloc` suffices here

File: libfreerdp/core/update.c (hunk 1 above)
Comment (akallabeth) [reply libfreerdp/core/update.c]: No, the data contained is a color poiner.

**Comment by akallabeth** [comment]
@mfleisz Regarding additional allocations, for that reason I've added the context argument to all functions to make it easy to exchange the `malloc` and `free` with a streampool

File: libfreerdp/core/update.c (hunk 1 above)
Comment (mfleisz) [reply libfreerdp/core/update.c]: Yes - you'r right 👍

File: libfreerdp/core/message.c [hunk 9]
```diff
@@ -244,26 +244,11 @@ static BOOL update_message_SurfaceBits(rdpContext* context,
...
 		return FALSE;
 
-	wParam = (SURFACE_BITS_COMMAND*) malloc(sizeof(SURFACE_BITS_COMMAND));
+	wParam = copy_surface_bits_command(context, surfaceBitsCommand);
 
 	if (!wParam)
 		return FALSE;
 
-	CopyMemory(wParam, surfaceBitsCommand, sizeof(SURFACE_BITS_COMMAND));
-#ifdef WITH_STREAM_POOL
```
Comment (mfleisz) [inline libfreerdp/core/message.c]: Not quite sure but there is one more place in code that uses #ifdef WITH_STREAM_POOL.
As WITH_STREAM_POOL is defined on top of the source file I think this line should be removed as well as this could lead to some unwanted behavior?

File: libfreerdp/cache/cache.c [hunk 10]
```diff
@@ -90,3 +92,53 @@ void cache_free(rdpCache* cache)
...
+
+	if (!dst->bmp.bitmapData)
+		goto fail;
+
+	CopyMemory(dst->bmp.bitmapData, order->bmp.bitmapData,
+			   order->bmp.bitmapDataLength);
+
+	return dst;
+
+	fail:
```
Comment (hardening) [inline libfreerdp/cache/cache.c]: code style typo
