### PR TITLE
Silence WLog_ERR messages if last error is set.

### LINKED ISSUE #4145: "freerdp_check_fds() failed" when exiting xfreerdp
I'm using the current master version of 2017-09-23.
When I exit xfreerdp, I get this:
`
...
[19:27:05:339] [19116:19117] [INFO][com.freerdp.core] - ERRINFO_LOGOFF_BY_USER (0x0000000C):The disconnection was initiated by the user logging off his or her session on the server.
[19:27:05:461] [19116:19117] [ERROR][com.freerdp.core] - freerdp_check_fds() failed - 0
[19:27:05:461] [19116:19117] [ERROR][com.freerdp.client.x11] - Failed to check FreeRDP file descriptor
`
The last two lines are new and indicate a problem. 

build config:
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX:PATH=/usr -DCMAKE_INSTALL_LIBDIR:PATH=lib -DCMAKE_SKIP_INSTALL_RPATH=ON -DWITH_CUPS=ON -DWITH_CLIENT=ON -DWITH_PCSC=ON -DWITH_ALSA=ON -DWITH_PULSE=ON -DWITH_OSS=OFF -DWITH_DIRECTFB=OFF -DWITH_JPEG=ON -DWITH_GSM=ON -DWITH_GSTREAMER_1_0=ON -DWITH_IPP=OFF -DWITH_OPENSSL=ON -DWITH_CHANNELS=ON -DWITH_X11=ON -DWITH_XCURSOR=ON -DWITH_XEXT=ON -DWITH_XKBFILE=ON -DWITH_XI=ON -DWITH_XINERAMA=ON -DWITH_XRENDER=ON -DWITH_XV=ON -DWITH_ZLIB=ON -DWITH_KRB5=ON -DBUILTIN_CHANNELS=OFF -DWITH_SERVER=OFF -DWITH_SSE2=ON -DWITH_DEBUG_SCARD=OFF -DWITH_SMARTCARD_INSPECT=ON -DWITH_WAYLAND=ON -DWITH_LIBSYSTEMD=ON -DCMAKE_NO_BUILTIN_CHRPATH=ON .

parameters:
xfreerdp /u:myusername  /f +clipboard +wallpaper /v:192.168.0.75 /sound:sys:pulse /drive:hendhome,/home/hendrik

### PR DESCRIPTION
**Pull request by akallabeth**
Fixes #4145

### CODE REVIEW

File: client/Sample/freerdp.c [hunk 1]
```diff
@@ -146,7 +146,9 @@ static void* tf_client_thread_proc(freerdp* instance)
 
 		if (!freerdp_check_event_handles(instance->context))
 		{
-			WLog_ERR(TAG, "Failed to check FreeRDP event handles");
+			if (freerdp_get_last_error(instance->context) == FREERDP_ERROR_SUCCESS)
```
Comment (mfleisz) [inline client/Sample/freerdp.c]: Think that should be !=

File: client/Wayland/wlfreerdp.c [hunk 2]
```diff
@@ -346,7 +345,9 @@ static int wlfreerdp_run(freerdp* instance)
 		//if (WaitForMultipleObjects(count, &handles[1], FALSE, INFINITE)) {
 		if (freerdp_check_event_handles(instance->context) != TRUE)
 		{
-			printf("Failed to check FreeRDP file descriptor\n");
+			if (freerdp_get_last_error(instance->context) == FREERDP_ERROR_SUCCESS)
```
Comment (mfleisz) [inline client/Wayland/wlfreerdp.c]: Again should be !=

File: client/Sample/freerdp.c (hunk 1 above)
Comment (akallabeth) [reply client/Sample/freerdp.c]: No, only print something if no error has been set (which already printed a more detailed error message)

File: client/Wayland/wlfreerdp.c (hunk 2 above)
Comment (akallabeth) [reply client/Wayland/wlfreerdp.c]: No, only print something if no error has been set (which already printed a more detailed error message)

File: client/Sample/freerdp.c (hunk 1 above)
Comment (mfleisz) [reply client/Sample/freerdp.c]: Ah sorry - thought the "Failed to check FreeRDP event handles" message in case of ERROR_SUCCESS was the problem ... alright then it LGTM
