### PR TITLE
Fixed #4995: Don't forget to send the NULL of the clipboard string.

### LINKED ISSUE #4995: Copy/paste issue under MAC RDP
When I do copy/paste under mac RDP version (not the Prebuilt version), the last character of the copied content is missing. Did anyone get the same issue?

### LINKED ISSUE #4999: Attempt to copy file on guest crashes the app
Environment:
* Host is Windows 10 Home, FreeRDP 2.0.0-dev4 compiled on MS Visual Studio 2015 Community
* Guest is Windows 10 Home with RDP enabled via rdpwrap

Steps to reproduce:

1. Connect to the guest system:
 

>  wfreerdp.exe /v:192.168.100.225 /u:**** /p:**** /log-level:trace

2. Open Windows Explorer on the remote desktop, select a file and press Ctrl+C. The application crashes with:

```
Exception thrown at 0x74A6E4A2 (combase.dll) in wfreerdp.exe: 0xC0000005: Access violation reading location 0xDDDDDDE5.

The program '[13364] wfreerdp.exe' has exited with code 0 (0x0).

```
The stack:
```
 	combase.dll!74a6e4a2()	Unknown
 	[Frames below may be incorrect and/or missing, no symbols loaded for combase.dll]	
 	[External Code]	
	wfreerdp.exe!cliprdr_thread_func(void * arg) Line 1592	C
 	[External Code]	

```
Is copying of files from the remote system to the local one supported? I was looking for any hints and I only found this task list saying it's incomplete:

https://github.com/ilammy/FreeRDP/issues/5

It should not however crash the client application.

### PR DESCRIPTION
**Pull request by akallabeth**

### CODE REVIEW

File: client/Mac/MRDPView.m [hunk 1]
```diff
@@ -769,7 +769,8 @@ - (void) onPasteboardTimerFired :(NSTimer*) timer
 			formatId = ClipboardRegisterFormat(mfc->clipboard, "UTF8_STRING");
 			size = (UINT32) [formatData length];
 			data = [formatData bytes];
-			ClipboardSetData(mfc->clipboard, formatId, data, size);
+			/* size is the string length without the terminating NULL terminator */
+			ClipboardSetData(mfc->clipboard, formatId, data, size + 1);
```
Comment (mfleisz) [inline client/Mac/MRDPView.m]: Are you sure data is pointing to a buffer with a valid length of ```size + 1```? If the trailing zero would be part of formatData I'd expect ```[formatData length]``` to return the size including the trailing \0.

Comment (akallabeth) [reply client/Mac/MRDPView.m]: @mfleisz `[formatData length]` behaves like `strlen` and returns the length without the trailing zero.
